/**
 *
 * @author BLAXK
 */
public class PersonalDataForm extends javax.swing.JFrame {

    /**
     * Creates new form PersonalDataForm
     */
    public PersonalDataForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPartPanel = new javax.swing.JPanel();
        TopCenterLabel = new javax.swing.JLabel();
        InfoPartPanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        AddrLabel = new javax.swing.JLabel();
        DisplayDataLabel = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        InputNameTextField = new javax.swing.JTextField();
        AddrScrollPane = new javax.swing.JScrollPane();
        AddrTextArea = new javax.swing.JTextArea();
        DisplayDataScrollPane = new javax.swing.JScrollPane();
        DisplayDataTextArea = new javax.swing.JTextArea();
        ButtonPartPanel = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        AddNameButton = new javax.swing.JButton();
        AddrButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Personal Data");
        setResizable(false);

        MainPartPanel.setBackground(new java.awt.Color(204, 255, 255));

        TopCenterLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        TopCenterLabel.setForeground(new java.awt.Color(0, 0, 0));
        TopCenterLabel.setText("Personal Data");

        InfoPartPanel.setBackground(new java.awt.Color(255, 204, 153));
        InfoPartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 0, 0));
        NameLabel.setText("Name :");

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(0, 0, 0));
        GenderLabel.setText("Gender :");

        AddrLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AddrLabel.setForeground(new java.awt.Color(0, 0, 0));
        AddrLabel.setText("Address :");

        DisplayDataLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        DisplayDataLabel.setForeground(new java.awt.Color(0, 0, 0));
        DisplayDataLabel.setText("Display Data :");

        MaleRadioButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        MaleRadioButton.setText("Male");
        MaleRadioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });

        FemaleRadioButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        FemaleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        InputNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        InputNameTextField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        InputNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        InputNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InputNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AddrTextArea.setBackground(new java.awt.Color(255, 255, 255));
        AddrTextArea.setColumns(20);
        AddrTextArea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AddrTextArea.setForeground(new java.awt.Color(0, 0, 0));
        AddrTextArea.setLineWrap(true);
        AddrTextArea.setRows(5);
        AddrTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AddrScrollPane.setViewportView(AddrTextArea);

        DisplayDataTextArea.setEditable(false);
        DisplayDataTextArea.setBackground(new java.awt.Color(255, 255, 255));
        DisplayDataTextArea.setColumns(20);
        DisplayDataTextArea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        DisplayDataTextArea.setForeground(new java.awt.Color(0, 0, 0));
        DisplayDataTextArea.setLineWrap(true);
        DisplayDataTextArea.setRows(5);
        DisplayDataTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DisplayDataTextArea.setFocusable(false);
        DisplayDataScrollPane.setViewportView(DisplayDataTextArea);

        javax.swing.GroupLayout InfoPartPanelLayout = new javax.swing.GroupLayout(InfoPartPanel);
        InfoPartPanel.setLayout(InfoPartPanelLayout);
        InfoPartPanelLayout.setHorizontalGroup(
            InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPartPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPartPanelLayout.createSequentialGroup()
                        .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderLabel))
                        .addGap(86, 86, 86)
                        .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InfoPartPanelLayout.createSequentialGroup()
                                .addComponent(MaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(InfoPartPanelLayout.createSequentialGroup()
                        .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddrLabel)
                            .addComponent(DisplayDataLabel))
                        .addGap(43, 43, 43)
                        .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddrScrollPane)
                            .addComponent(DisplayDataScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        InfoPartPanelLayout.setVerticalGroup(
            InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPartPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(29, 29, 29)
                .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton)
                    .addComponent(GenderLabel))
                .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPartPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AddrLabel))
                    .addGroup(InfoPartPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AddrScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(InfoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPartPanelLayout.createSequentialGroup()
                        .addComponent(DisplayDataLabel)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPartPanelLayout.createSequentialGroup()
                        .addComponent(DisplayDataScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        ButtonPartPanel.setBackground(new java.awt.Color(204, 204, 204));

        ExitButton.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.MatteBorder(null));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AddNameButton.setBackground(new java.awt.Color(102, 255, 102));
        AddNameButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        AddNameButton.setForeground(new java.awt.Color(0, 0, 0));
        AddNameButton.setText("Add Name");
        AddNameButton.setBorder(new javax.swing.border.MatteBorder(null));
        AddNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNameButtonActionPerformed(evt);
            }
        });

        AddrButton.setBackground(new java.awt.Color(102, 102, 255));
        AddrButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        AddrButton.setForeground(new java.awt.Color(0, 0, 0));
        AddrButton.setText("Add Addr");
        AddrButton.setBorder(new javax.swing.border.MatteBorder(null));
        AddrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddrButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(255, 153, 51));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Clear");
        ClearButton.setBorder(new javax.swing.border.MatteBorder(null));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPartPanelLayout = new javax.swing.GroupLayout(ButtonPartPanel);
        ButtonPartPanel.setLayout(ButtonPartPanelLayout);
        ButtonPartPanelLayout.setHorizontalGroup(
            ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(AddNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(453, Short.MAX_VALUE)))
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(AddrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPartPanelLayout.createSequentialGroup()
                    .addContainerGap(306, Short.MAX_VALUE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(163, 163, 163)))
        );
        ButtonPartPanelLayout.setVerticalGroup(
            ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AddNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AddrButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ButtonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPartPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout MainPartPanelLayout = new javax.swing.GroupLayout(MainPartPanel);
        MainPartPanel.setLayout(MainPartPanelLayout);
        MainPartPanelLayout.setHorizontalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TopCenterLabel)
                .addGap(161, 161, 161))
            .addComponent(ButtonPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InfoPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPartPanelLayout.setVerticalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TopCenterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  title, message, type);
    }
    
    public String getGender() {
        return gender;
    }
    
    public String getAddrTextArea() {
        return AddrTextArea.getText();
    }
    
    public String getInputNameTextField() {
        return InputNameTextField.getText();
    }
    
    private int getButtonPattern() {
        return buttonPattern;
    }
    
    private void setButtonPattern(int buttonPattern) {
        this.buttonPattern = buttonPattern;
    }
    
    private void setGender(String gender) { 
        this.gender = gender;
    }
    
    private void setEnableRadioButton() {
        if(MaleRadioButton.isSelected()) {
            FemaleRadioButton.setEnabled(false);
            setGender(MaleRadioButton.getText());
        }
        else if (FemaleRadioButton.isSelected()) {
            MaleRadioButton.setEnabled(false);
            setGender(FemaleRadioButton.getText());
        }
        else {
            MaleRadioButton.setEnabled(true);
            FemaleRadioButton.setEnabled(true);
        }
    }
    
    private void addNameCondition() {
        if(getInputNameTextField().isEmpty()) {
            callOptionPane("Name Required ", "Please Enter Your Name!", 2);
        }
        else if (!MaleRadioButton.isSelected() && !FemaleRadioButton.isSelected()) {
            callOptionPane("Select Gender Required ", "Please select your gender!", 2);
        }
        else {
            if(getButtonPattern() == 0) {
                DisplayDataTextArea.append("Name : " + getInputNameTextField() + "\n");
                DisplayDataTextArea.append("Gender : " + getGender() + "\n");    
                setButtonPattern(1);
            }
            else {
                callOptionPane("Add Addresss Required ", "Please add an Address!", 0);
            }
        }
    }
    
    private void addAddressCondition() {
        if(getAddrTextArea().isEmpty()) {
            callOptionPane("Input Required ", "Please Enter Your Address!", 2);
        }
        else {
            if(getButtonPattern() == 1) {
                DisplayDataTextArea.append("Address : " + getAddrTextArea() + "\n\n");
                setButtonPattern(0);
            }
            else {
                callOptionPane("Add Name Required ", "Please add name first!", 0);
            }
        }
    }
    
    private void resetComponent() {
        InputNameTextField.setText("");
        MaleRadioButton.setSelected(false);
        FemaleRadioButton.setSelected(false);
        MaleRadioButton.setEnabled(true);
        FemaleRadioButton.setEnabled(true);
        AddrTextArea.setText("");
        DisplayDataTextArea.setText("");        
    }
    
    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        setEnableRadioButton();
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        setEnableRadioButton();
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        ExitDialog exit = new ExitDialog(this);
        exit.setLocationRelativeTo(this);
        exit.setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNameButtonActionPerformed
        addNameCondition();
    }//GEN-LAST:event_AddNameButtonActionPerformed

    private void AddrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddrButtonActionPerformed
        addAddressCondition();
    }//GEN-LAST:event_AddrButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        resetComponent();
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDataForm().setVisible(true);
            }
        });
    }

    private String gender;
    private int buttonPattern = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNameButton;
    private javax.swing.JButton AddrButton;
    private javax.swing.JLabel AddrLabel;
    private javax.swing.JScrollPane AddrScrollPane;
    private javax.swing.JTextArea AddrTextArea;
    private javax.swing.JPanel ButtonPartPanel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel DisplayDataLabel;
    private javax.swing.JScrollPane DisplayDataScrollPane;
    private javax.swing.JTextArea DisplayDataTextArea;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JPanel InfoPartPanel;
    private javax.swing.JTextField InputNameTextField;
    private javax.swing.JPanel MainPartPanel;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel TopCenterLabel;
    // End of variables declaration//GEN-END:variables
}
