/**
 *
 * @author BLAXK
 */

public class NumberGuesser extends javax.swing.JFrame {

    /**
     * Creates new form NumberGuesser
     */
    public NumberGuesser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageLabel = new javax.swing.JLabel();
        RightPartPanel = new javax.swing.JPanel();
        GuessButton = new javax.swing.JButton();
        InputTextField = new javax.swing.JTextField();
        RandomNumberTextField = new javax.swing.JTextField();
        InfoLabel = new javax.swing.JLabel();
        NGGLabel = new javax.swing.JLabel();
        RandomNumbersLabel = new javax.swing.JLabel();
        TopLeftPartPanel = new javax.swing.JPanel();
        WinPartPanel = new javax.swing.JPanel();
        WinLabel = new javax.swing.JLabel();
        NumOfWinLabel = new javax.swing.JLabel();
        LosePartPanel = new javax.swing.JPanel();
        NumOfLoseLabel = new javax.swing.JLabel();
        LoseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guesser");
        setResizable(false);

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/question.jpg"))); // NOI18N

        RightPartPanel.setBackground(new java.awt.Color(0, 0, 0));

        GuessButton.setBackground(new java.awt.Color(255, 153, 0));
        GuessButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        GuessButton.setForeground(new java.awt.Color(0, 0, 0));
        GuessButton.setText("Guess");
        GuessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuessButtonActionPerformed(evt);
            }
        });

        InputTextField.setBackground(new java.awt.Color(0, 255, 255));
        InputTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        InputTextField.setForeground(new java.awt.Color(0, 0, 0));
        InputTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InputTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        InputTextField.setSelectionColor(new java.awt.Color(0, 0, 255));
        InputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputTextFieldKeyTyped(evt);
            }
        });

        RandomNumberTextField.setEditable(false);
        RandomNumberTextField.setBackground(new java.awt.Color(102, 102, 255));
        RandomNumberTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RandomNumberTextField.setForeground(new java.awt.Color(0, 0, 0));
        RandomNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RandomNumberTextField.setText("?");
        RandomNumberTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RandomNumberTextField.setFocusable(false);

        InfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InfoLabel.setForeground(new java.awt.Color(255, 255, 51));
        InfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoLabel.setText("Enter the guessed number");

        NGGLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NGGLabel.setForeground(new java.awt.Color(255, 255, 51));
        NGGLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NGGLabel.setText("Number Guesser Game");
        NGGLabel.setToolTipText("");

        RandomNumbersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RandomNumbersLabel.setForeground(new java.awt.Color(255, 255, 51));
        RandomNumbersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RandomNumbersLabel.setText("0 To 100");

        javax.swing.GroupLayout RightPartPanelLayout = new javax.swing.GroupLayout(RightPartPanel);
        RightPartPanel.setLayout(RightPartPanelLayout);
        RightPartPanelLayout.setHorizontalGroup(
            RightPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NGGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPartPanelLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(RightPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RandomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RightPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPartPanelLayout.createSequentialGroup()
                            .addComponent(RandomNumbersLabel)
                            .addGap(84, 84, 84))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPartPanelLayout.createSequentialGroup()
                            .addComponent(InputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)))
                    .addComponent(InfoLabel)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        RightPartPanelLayout.setVerticalGroup(
            RightPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPartPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(NGGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RandomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(RandomNumbersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(GuessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        TopLeftPartPanel.setBackground(new java.awt.Color(0, 0, 0));

        WinPartPanel.setBackground(new java.awt.Color(51, 255, 0));

        WinLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WinLabel.setForeground(new java.awt.Color(0, 0, 0));
        WinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinLabel.setText("W");

        NumOfWinLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NumOfWinLabel.setForeground(new java.awt.Color(0, 0, 0));
        NumOfWinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfWinLabel.setText("0");

        javax.swing.GroupLayout WinPartPanelLayout = new javax.swing.GroupLayout(WinPartPanel);
        WinPartPanel.setLayout(WinPartPanelLayout);
        WinPartPanelLayout.setHorizontalGroup(
            WinPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WinPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumOfWinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        WinPartPanelLayout.setVerticalGroup(
            WinPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NumOfWinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LosePartPanel.setBackground(new java.awt.Color(255, 0, 51));

        NumOfLoseLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NumOfLoseLabel.setForeground(new java.awt.Color(0, 0, 0));
        NumOfLoseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfLoseLabel.setText("0");

        LoseLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoseLabel.setForeground(new java.awt.Color(0, 0, 0));
        LoseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoseLabel.setText("L");

        javax.swing.GroupLayout LosePartPanelLayout = new javax.swing.GroupLayout(LosePartPanel);
        LosePartPanel.setLayout(LosePartPanelLayout);
        LosePartPanelLayout.setHorizontalGroup(
            LosePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LosePartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LosePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumOfLoseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LosePartPanelLayout.setVerticalGroup(
            LosePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LosePartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NumOfLoseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TopLeftPartPanelLayout = new javax.swing.GroupLayout(TopLeftPartPanel);
        TopLeftPartPanel.setLayout(TopLeftPartPanelLayout);
        TopLeftPartPanelLayout.setHorizontalGroup(
            TopLeftPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WinPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LosePartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLeftPartPanelLayout.setVerticalGroup(
            TopLeftPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLeftPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LosePartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WinPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TopLeftPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(RightPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TopLeftPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SwapImage(char status) {
        switch (status) {
            case 'W':
                ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/good_1.gif")));
                break;
            case 'L':
                ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/tryagain.gif")));
                break;
            default:
                ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/question.jpg")));
        }

        if (Timer == null) {
            Timer = new javax.swing.Timer(2000, e -> {
                ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/question.jpg")));
                RandomNumberTextField.setText("?");
                InputTextField.setText("");
                GuessButton.setEnabled(true);
            });
            Timer.setRepeats(false);
        }
        Timer.restart();
    }

    
    private String RandomNumber() {
        return Integer.toString(new java.util.Random().nextInt(101));
    }
    
    private void CheckAnswer() {
        RandomNumberTextField.setText(RandomNumber());
        if(InputTextField.getText().equals(RandomNumberTextField.getText())) {
            NumOfWinLabel.setText(Integer.toString(++win));
            SwapImage('W');
        }
        else {
            NumOfLoseLabel.setText(Integer.toString(++lose));
            SwapImage('L');
        }
    }
    
    
    private void GuessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuessButtonActionPerformed
        if(InputTextField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your guessed numbers!!" , "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else {
            CheckAnswer();
            GuessButton.setEnabled(false);
        }
    }//GEN-LAST:event_GuessButtonActionPerformed

    private void InputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTextFieldKeyTyped
        char val = evt.getKeyChar();
        if (!Character.isDigit(val)) {
            evt.consume();
        }
    }//GEN-LAST:event_InputTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGuesser().setVisible(true);
            }
        });
    }

    private int win = 0;
    private int lose = 0;
    private javax.swing.Timer Timer;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuessButton;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JTextField InputTextField;
    private javax.swing.JLabel LoseLabel;
    private javax.swing.JPanel LosePartPanel;
    private javax.swing.JLabel NGGLabel;
    private javax.swing.JLabel NumOfLoseLabel;
    private javax.swing.JLabel NumOfWinLabel;
    private javax.swing.JTextField RandomNumberTextField;
    private javax.swing.JLabel RandomNumbersLabel;
    private javax.swing.JPanel RightPartPanel;
    private javax.swing.JPanel TopLeftPartPanel;
    private javax.swing.JLabel WinLabel;
    private javax.swing.JPanel WinPartPanel;
    // End of variables declaration//GEN-END:variables
}
