/**
 *
 * @author BLAXK
 */

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.ArrayList;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

class QuestionJson {
    String question;
    List<String> choices;
    String fiftyFifty;
    String answer;
}

public class QuestionGame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public QuestionGame() {
        initComponents();
        setLocationRelativeTo(this);
        questionData = getQuestionJson();
        setQuestionDetail(questionNumber);
        soundController = new SoundController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoiceButtonGroup = new javax.swing.ButtonGroup();
        MainPartPanel = new javax.swing.JPanel();
        QuestionGameLabel = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        PointLabel = new javax.swing.JLabel();
        AnswerButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        QuestionPartPanel = new javax.swing.JPanel();
        QuestionLabel = new javax.swing.JLabel();
        Choice1RadioButton = new javax.swing.JRadioButton();
        Choice2RadioButton = new javax.swing.JRadioButton();
        Choice3RadioButton = new javax.swing.JRadioButton();
        Choice4RadioButton = new javax.swing.JRadioButton();
        fiftyFiftyLabel = new javax.swing.JLabel();
        fiftyFiftyButton = new javax.swing.JButton();
        NumberQuestionsPartPanel = new javax.swing.JPanel();
        Question1Label = new javax.swing.JLabel();
        Question2Label = new javax.swing.JLabel();
        Question3Label = new javax.swing.JLabel();
        Question4Label = new javax.swing.JLabel();
        Question5Label = new javax.swing.JLabel();
        Question6Label = new javax.swing.JLabel();
        Question7Label = new javax.swing.JLabel();
        Question8Label = new javax.swing.JLabel();
        Question9Label = new javax.swing.JLabel();
        Question10Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question Game");
        setResizable(false);

        MainPartPanel.setBackground(new java.awt.Color(51, 51, 51));

        QuestionGameLabel.setBackground(new java.awt.Color(255, 255, 255));
        QuestionGameLabel.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        QuestionGameLabel.setForeground(new java.awt.Color(255, 153, 51));
        QuestionGameLabel.setText("Question Game");

        ScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(0, 255, 204));
        ScoreLabel.setText("Score");

        PointLabel.setBackground(new java.awt.Color(0, 0, 0));
        PointLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PointLabel.setForeground(new java.awt.Color(0, 255, 255));
        PointLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PointLabel.setText("0");
        PointLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        PointLabel.setOpaque(true);

        AnswerButton.setBackground(new java.awt.Color(51, 255, 51));
        AnswerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AnswerButton.setForeground(new java.awt.Color(0, 0, 0));
        AnswerButton.setText("Answer");
        AnswerButton.setToolTipText("");
        AnswerButton.setBorder(new javax.swing.border.MatteBorder(null));
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 0, 0));
        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.MatteBorder(null));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        QuestionPartPanel.setBackground(new java.awt.Color(204, 204, 204));
        QuestionPartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        QuestionLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        QuestionLabel.setForeground(new java.awt.Color(0, 0, 0));
        QuestionLabel.setText("Question");

        ChoiceButtonGroup.add(Choice1RadioButton);
        Choice1RadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choice1RadioButton.setForeground(new java.awt.Color(0, 0, 0));
        Choice1RadioButton.setText("Choice 1");

        ChoiceButtonGroup.add(Choice2RadioButton);
        Choice2RadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choice2RadioButton.setForeground(new java.awt.Color(0, 0, 0));
        Choice2RadioButton.setText("Choice 2");

        ChoiceButtonGroup.add(Choice3RadioButton);
        Choice3RadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choice3RadioButton.setForeground(new java.awt.Color(0, 0, 0));
        Choice3RadioButton.setText("Choice 3");

        ChoiceButtonGroup.add(Choice4RadioButton);
        Choice4RadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choice4RadioButton.setForeground(new java.awt.Color(0, 0, 0));
        Choice4RadioButton.setText("Choice 4");

        fiftyFiftyLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        fiftyFiftyLabel.setForeground(new java.awt.Color(0, 0, 153));
        fiftyFiftyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiftyFiftyLabel.setText("50:50");

        fiftyFiftyButton.setBackground(new java.awt.Color(255, 255, 255));
        fiftyFiftyButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fiftyFiftyButton.setForeground(new java.awt.Color(0, 0, 0));
        fiftyFiftyButton.setText("x3");
        fiftyFiftyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyFiftyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuestionPartPanelLayout = new javax.swing.GroupLayout(QuestionPartPanel);
        QuestionPartPanel.setLayout(QuestionPartPanelLayout);
        QuestionPartPanelLayout.setHorizontalGroup(
            QuestionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPartPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(QuestionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choice1RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice2RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice3RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice4RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(QuestionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiftyFiftyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiftyFiftyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(QuestionPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuestionPartPanelLayout.setVerticalGroup(
            QuestionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(QuestionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionPartPanelLayout.createSequentialGroup()
                        .addComponent(fiftyFiftyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fiftyFiftyButton))
                    .addGroup(QuestionPartPanelLayout.createSequentialGroup()
                        .addComponent(Choice1RadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(Choice2RadioButton)
                        .addGap(15, 15, 15)
                        .addComponent(Choice3RadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(Choice4RadioButton)))
                .addGap(32, 32, 32))
        );

        NumberQuestionsPartPanel.setBackground(new java.awt.Color(0, 0, 0));
        NumberQuestionsPartPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NumberQuestionsPartPanel.setForeground(new java.awt.Color(255, 255, 0));

        Question1Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question1Label.setForeground(new java.awt.Color(255, 255, 0));
        Question1Label.setText("1");

        Question2Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question2Label.setForeground(new java.awt.Color(255, 255, 0));
        Question2Label.setText("2");

        Question3Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question3Label.setForeground(new java.awt.Color(255, 255, 0));
        Question3Label.setText("3");

        Question4Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question4Label.setForeground(new java.awt.Color(255, 255, 0));
        Question4Label.setText("4");

        Question5Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question5Label.setForeground(new java.awt.Color(255, 255, 0));
        Question5Label.setText("5");

        Question6Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question6Label.setForeground(new java.awt.Color(255, 255, 0));
        Question6Label.setText("6");

        Question7Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question7Label.setForeground(new java.awt.Color(255, 255, 0));
        Question7Label.setText("7");

        Question8Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question8Label.setForeground(new java.awt.Color(255, 255, 0));
        Question8Label.setText("8");

        Question9Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question9Label.setForeground(new java.awt.Color(255, 255, 0));
        Question9Label.setText("9");

        Question10Label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Question10Label.setForeground(new java.awt.Color(255, 255, 0));
        Question10Label.setText("10");

        javax.swing.GroupLayout NumberQuestionsPartPanelLayout = new javax.swing.GroupLayout(NumberQuestionsPartPanel);
        NumberQuestionsPartPanel.setLayout(NumberQuestionsPartPanelLayout);
        NumberQuestionsPartPanelLayout.setHorizontalGroup(
            NumberQuestionsPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberQuestionsPartPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Question1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Question2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Question3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Question9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Question10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NumberQuestionsPartPanelLayout.setVerticalGroup(
            NumberQuestionsPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberQuestionsPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberQuestionsPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberQuestionsPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Question3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberQuestionsPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Question1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Question2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPartPanelLayout = new javax.swing.GroupLayout(MainPartPanel);
        MainPartPanel.setLayout(MainPartPanelLayout);
        MainPartPanelLayout.setHorizontalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(MainPartPanelLayout.createSequentialGroup()
                .addGroup(MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPartPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPartPanelLayout.createSequentialGroup()
                                .addComponent(QuestionGameLabel)
                                .addGap(145, 145, 145)
                                .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QuestionPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPartPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(NumberQuestionsPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPartPanelLayout.setVerticalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionGameLabel))
                .addGap(33, 33, 33)
                .addComponent(NumberQuestionsPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(QuestionPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPartPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private List<QuestionJson> getQuestionJson() {
        try (InputStream inputStream = getClass().getResourceAsStream("/data/Question.json")) {
            InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8);
            return new Gson().fromJson(reader, new TypeToken<List<QuestionJson>>() {}.getType());
        } 
        catch (Exception e) {
            callOptionPane(e.toString(), "Error", 0);
            this.dispose();
            return null;
         } 
    }
    
    public List<String> getQuestion() {
        List<String> questionList = new ArrayList<>();
        
        for (QuestionJson q : questionData) {
            questionList.add(q.question);
        }
        return questionList;
    }
    
    public List<String> getCorrectAnswer() {
        List<String> answerList = new ArrayList<>();
        
        for (QuestionJson q : questionData) {
            answerList.add(q.answer);
        }
        return answerList;
    }
    
    public List<String> getFiftyFiftyChoice() {
        List<String> fiftyChoiceList = new ArrayList<>();
        
        for (QuestionJson q : questionData) {
            fiftyChoiceList.add(q.fiftyFifty);
        }
        return fiftyChoiceList;
    }
    
    public List<List<String>> getChoices() {
        List<List<String>> choiceList = new ArrayList<>();
        
        for (QuestionJson q : questionData) {
            choiceList.add(q.choices);
        }
        return choiceList;
    }
    
    private javax.swing.JRadioButton[] getRadioButtonComponent() {
        return new javax.swing.JRadioButton[] {
            Choice1RadioButton, 
            Choice2RadioButton, 
            Choice3RadioButton, 
            Choice4RadioButton
        };
    }
    
    private javax.swing.JLabel[] getNumberQuestionLabel() {
        return new javax.swing.JLabel[] {
            Question1Label,
            Question2Label,
            Question3Label,
            Question4Label,
            Question5Label,
            Question6Label,
            Question7Label,
            Question8Label,
            Question9Label,
            Question10Label,
        };
    }
        
    private void setPointLabel(String point) {
        PointLabel.setText(point);
    }
        
    private void setSymbolQuestionLabel(int index, boolean isCorrect) {
        if(isCorrect) {
            getNumberQuestionLabel()[index].setForeground(java.awt.Color.GREEN);
            getNumberQuestionLabel()[index].setText("\u2713");
        }
        else {
            getNumberQuestionLabel()[index].setForeground(java.awt.Color.RED);
            getNumberQuestionLabel()[index].setText("\u2718");
        }
    }
    
    private void setQuestionDetail(int index) {
        QuestionLabel.setText("<html>" + getQuestion().get(index) + "</html>");
        List<String> choiceNumber = getChoices().get(index);
        java.util.Collections.shuffle(choiceNumber);
        
        for (int indexs = 0; indexs < choiceNumber.size(); indexs++) {
            getRadioButtonComponent()[indexs].setText(choiceNumber.get(indexs));
            getRadioButtonComponent()[indexs].setActionCommand(choiceNumber.get(indexs));
        }
    }
    
    private void setEnableRadioButton(boolean status) {
         for (javax.swing.JRadioButton component : getRadioButtonComponent()) {
             component.setEnabled(status);
         }
    }
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  message, title, type);
    }
    
    private void checkAnswer(int index) {
        javax.swing.ButtonModel selectedModel = ChoiceButtonGroup.getSelection();        
        if(selectedModel != null) {
            //Answer's correct
            if (selectedModel.getActionCommand().equalsIgnoreCase(getCorrectAnswer().get(index))) {
                playSound(0, 500);
                if(helperQuantity > 0) {
                    fiftyFiftyButton.setEnabled(true);
                }
                setEnableRadioButton(true);
                setPointLabel(Integer.toString(++score));
                ChoiceButtonGroup.clearSelection();
                setSymbolQuestionLabel(questionNumber, true);
                questionNumber++;
                if (questionNumber < getQuestion().size()) {
                    setQuestionDetail(questionNumber);
                    return;
                } 
                gameWin();
            }
            //Answer's wrong
            else {
                playSound(1, 500);
                gameLose = true;
                setSymbolQuestionLabel(questionNumber, false);
                setEnableRadioButton(false);
                swapButton();
            }
        } 
        else {
            callOptionPane("Please choose your answer", "Answer Required", 2);
        }
    }
    
    private void gameWin() {
        gameLose = true;
        fiftyFiftyButton.setEnabled(false);
        setEnableRadioButton(false);
        playSound(2, 500);
        callOptionPane("Congratulations, you won this game", "Congratulations", 1);
        swapButton();
    }
    
    private void swapButton() {
        if(gameLose) {
            AnswerButton.setBackground(java.awt.Color.ORANGE);
            AnswerButton.setText("Retry");
            return;
        }
        AnswerButton.setBackground(java.awt.Color.GREEN);
        AnswerButton.setText("Answer");
    }
    
    private void fiftyFiftyHelper(int index) {        
        fiftyFiftyButton.setText("x" + (--helperQuantity));
        fiftyFiftyButton.setEnabled(false);
        ChoiceButtonGroup.clearSelection();
        
        for (int i = 0; i < getChoices().get(index).size(); i++) {

            boolean answer = getRadioButtonComponent()[i].getText().equalsIgnoreCase(getCorrectAnswer().get(index));
            boolean fiftyFiftyChoice = getRadioButtonComponent()[i].getText().equalsIgnoreCase(getFiftyFiftyChoice().get(index));
            
            if (answer || fiftyFiftyChoice ) {
                getRadioButtonComponent()[i].setEnabled(true);
            }
            else {
                getRadioButtonComponent()[i].setEnabled(false);
            }
        }
    }
    
    private void resetComponent() {            
        if(gameLose) {
            for(int index = 0; index < getQuestion().size(); index++) {
                getNumberQuestionLabel()[index].setForeground(java.awt.Color.YELLOW);
                getNumberQuestionLabel()[index].setText(Integer.toString(index + 1));
            }
            score = 0;
            questionNumber = 0;
            helperQuantity = 3;
            gameLose = false;
            fiftyFiftyButton.setText("x" + helperQuantity);
            fiftyFiftyButton.setEnabled(true);
            ChoiceButtonGroup.clearSelection();
            setPointLabel("0"); 
            setEnableRadioButton(true);
            swapButton();
            setQuestionDetail(questionNumber);
        }
        return;
    }
    
    private void playSound(int selectSound, int sleepTime) {
        soundController.play(selectSound);
        try {
            Thread.sleep(sleepTime);
        } 
        catch (Exception e) {
            callOptionPane("Error", e.toString(), 0);
        }
    }
    
    private void fiftyFiftyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyFiftyButtonActionPerformed
        fiftyFiftyHelper(questionNumber);
    }//GEN-LAST:event_fiftyFiftyButtonActionPerformed
    
    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        if(gameLose){
            resetComponent();
            return;
        }
        checkAnswer(questionNumber);
    }//GEN-LAST:event_AnswerButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        soundController.close();
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionGame().setVisible(true);
            }
        });
    }
    
    public SoundController soundController;
    private int questionNumber = 0;
    private int helperQuantity = 3;
    private int score = 0;
    private boolean gameLose = false;
    private List<QuestionJson> questionData;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerButton;
    private javax.swing.JRadioButton Choice1RadioButton;
    private javax.swing.JRadioButton Choice2RadioButton;
    private javax.swing.JRadioButton Choice3RadioButton;
    private javax.swing.JRadioButton Choice4RadioButton;
    private javax.swing.ButtonGroup ChoiceButtonGroup;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel MainPartPanel;
    private javax.swing.JPanel NumberQuestionsPartPanel;
    private javax.swing.JLabel PointLabel;
    private javax.swing.JLabel Question10Label;
    private javax.swing.JLabel Question1Label;
    private javax.swing.JLabel Question2Label;
    private javax.swing.JLabel Question3Label;
    private javax.swing.JLabel Question4Label;
    private javax.swing.JLabel Question5Label;
    private javax.swing.JLabel Question6Label;
    private javax.swing.JLabel Question7Label;
    private javax.swing.JLabel Question8Label;
    private javax.swing.JLabel Question9Label;
    private javax.swing.JLabel QuestionGameLabel;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JPanel QuestionPartPanel;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JButton fiftyFiftyButton;
    private javax.swing.JLabel fiftyFiftyLabel;
    // End of variables declaration//GEN-END:variables
}