package com.github.blaxk3.fruit.shop;

import java.io.File;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BLAXK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        copyComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productPartPanel = new javax.swing.JPanel();
        shopLabel = new javax.swing.JLabel();
        productScrollPane = new javax.swing.JScrollPane();
        productListPartPanel = new javax.swing.JPanel();
        productPanelPrototype = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        productImageLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        productQtySpinner = new javax.swing.JSpinner();
        receiptPartPanel = new javax.swing.JPanel();
        receiptLabel = new javax.swing.JLabel();
        orderDetailScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        categoiresMenu = new javax.swing.JMenu();
        allFruitMenuItem = new javax.swing.JMenuItem();
        simpleFruitCBMI = new javax.swing.JCheckBoxMenuItem();
        aggregateFruitCBMI = new javax.swing.JCheckBoxMenuItem();
        multipleFruitCBMI = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fruit Shop");
        setName("mainFrame"); // NOI18N
        setResizable(false);

        productPartPanel.setBackground(new java.awt.Color(255, 255, 255));
        productPartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        shopLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        shopLabel.setForeground(new java.awt.Color(0, 0, 0));
        shopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopLabel.setText("Fruit Shop");
        shopLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        productListPartPanel.setBackground(new java.awt.Color(255, 255, 255));
        productListPartPanel.setPreferredSize(new java.awt.Dimension(223, 250));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20);
        flowLayout1.setAlignOnBaseline(true);
        productListPartPanel.setLayout(flowLayout1);

        productPanelPrototype.setBackground(new java.awt.Color(255, 255, 255));
        productPanelPrototype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        productPanelPrototype.setEnabled(false);
        productPanelPrototype.setPreferredSize(new java.awt.Dimension(224, 267));
        productPanelPrototype.setVisible(false);

        productNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        productNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNameLabel.setText("label");
        productNameLabel.setPreferredSize(new java.awt.Dimension(193, 22));

        productImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productImageLabel.setToolTipText("");
        productImageLabel.setIconTextGap(0);
        productImageLabel.setPreferredSize(new java.awt.Dimension(193, 170));

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 0, 0));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price :");
        priceLabel.setPreferredSize(new java.awt.Dimension(104, 17));

        productPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productPriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        productPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPriceLabel.setText("0 ฿");
        productPriceLabel.setPreferredSize(new java.awt.Dimension(80, 17));

        qtyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(0, 0, 0));
        qtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyLabel.setText("Quantity :");
        qtyLabel.setPreferredSize(new java.awt.Dimension(104, 17));

        productQtySpinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productQtySpinner.setModel(new javax.swing.SpinnerNumberModel());
        productQtySpinner.setPreferredSize(new java.awt.Dimension(83, 30));

        javax.swing.GroupLayout productPanelPrototypeLayout = new javax.swing.GroupLayout(productPanelPrototype);
        productPanelPrototype.setLayout(productPanelPrototypeLayout);
        productPanelPrototypeLayout.setHorizontalGroup(
            productPanelPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPrototypeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(productPanelPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productPanelPrototypeLayout.createSequentialGroup()
                        .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(productQtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPanelPrototypeLayout.createSequentialGroup()
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(productPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        productPanelPrototypeLayout.setVerticalGroup(
            productPanelPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPrototypeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(productImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(productPanelPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(productPanelPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        productListPartPanel.add(productPanelPrototype);

        productScrollPane.setViewportView(productListPartPanel);
        productListPartPanel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout productPartPanelLayout = new javax.swing.GroupLayout(productPartPanel);
        productPartPanel.setLayout(productPartPanelLayout);
        productPartPanelLayout.setHorizontalGroup(
            productPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPartPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(shopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(productScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        productPartPanelLayout.setVerticalGroup(
            productPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPartPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(shopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productScrollPane))
        );

        receiptPartPanel.setBackground(new java.awt.Color(255, 255, 255));
        receiptPartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        receiptLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        receiptLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receiptLabel.setText("Receipt");
        receiptLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextArea1.setFocusable(false);
        orderDetailScrollPane.setViewportView(jTextArea1);

        addButton.setBackground(new java.awt.Color(102, 255, 51));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 0, 0));
        addButton.setText("Add");
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receiptPartPanelLayout = new javax.swing.GroupLayout(receiptPartPanel);
        receiptPartPanel.setLayout(receiptPartPanelLayout);
        receiptPartPanelLayout.setHorizontalGroup(
            receiptPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPartPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(receiptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(receiptPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(receiptPartPanelLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderDetailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        receiptPartPanelLayout.setVerticalGroup(
            receiptPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPartPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(receiptLabel)
                .addGap(29, 29, 29)
                .addComponent(orderDetailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(receiptPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setForeground(new java.awt.Color(0, 0, 0));

        categoiresMenu.setText("Categories");
        categoiresMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        allFruitMenuItem.setText("All");
        categoiresMenu.add(allFruitMenuItem);

        simpleFruitCBMI.setText("Simple fruit");
        categoiresMenu.add(simpleFruitCBMI);

        aggregateFruitCBMI.setText("Aggregate fruit");
        categoiresMenu.add(aggregateFruitCBMI);

        multipleFruitCBMI.setText("Multiple fruit");
        categoiresMenu.add(multipleFruitCBMI);

        menuBar.add(categoiresMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiptPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(receiptPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBoxMenuItem aggregateFruitCBMI;
    private javax.swing.JMenuItem allFruitMenuItem;
    private javax.swing.JMenu categoiresMenu;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBoxMenuItem multipleFruitCBMI;
    private javax.swing.JScrollPane orderDetailScrollPane;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productImageLabel;
    private javax.swing.JPanel productListPartPanel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JPanel productPanelPrototype;
    private javax.swing.JPanel productPartPanel;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JSpinner productQtySpinner;
    private javax.swing.JScrollPane productScrollPane;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel receiptLabel;
    private javax.swing.JPanel receiptPartPanel;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JCheckBoxMenuItem simpleFruitCBMI;
    // End of variables declaration//GEN-END:variables
    private java.util.Map<String, java.net.URL> test = new java.util.HashMap<>(); 
    private java.util.List<String> productName = new java.util.ArrayList<>();
    private java.util.List<java.net.URL> productImge = new java.util.ArrayList<>();
    private javax.swing.JPanel[] productPanels;
    private javax.swing.JLabel[] copyProductNameLabel;
    private javax.swing.JLabel[] copyProductImageLabel;
    private javax.swing.JLabel[] copyPriceLabel;
    private javax.swing.JLabel[] copyProductPriceLabel ;
    private javax.swing.JLabel[] copyQtyLabel;
    private javax.swing.JSpinner[] copyProductQtySpinner;
    
//    record Info(URL url, JLabel label, JSpinner spinner) {}
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  message, title, type);
       
    }
    
    private void copyComponents() {
        try {
            int size = countImage(new File(getClass().getResource("/images").toURI()));
            int index = 0;
            resizePanel(size );
            productPanels = new javax.swing.JPanel[size];
            copyProductNameLabel = new javax.swing.JLabel[size];
            copyProductImageLabel = new javax.swing.JLabel[size];
            copyPriceLabel = new javax.swing.JLabel[size];
            copyProductPriceLabel = new javax.swing.JLabel[size];
            copyQtyLabel = new javax.swing.JLabel[size];
            copyProductQtySpinner = new javax.swing.JSpinner[size];
            
            for(javax.swing.JPanel copyProductPanels : productPanels) {
                copyProductPanels = new javax.swing.JPanel();
                copyProductPanels.setBackground(productPanelPrototype.getBackground());
                copyProductPanels.setBorder(productPanelPrototype.getBorder());
                copyProductPanels.setPreferredSize(productPanelPrototype.getPreferredSize());
                
                copyProductNameLabel[index] = new  javax.swing.JLabel();
                copyProductNameLabel[index].setHorizontalAlignment(productNameLabel.getHorizontalAlignment());
                copyProductNameLabel[index].setText(productName.get(index));
                copyProductNameLabel[index].setFont(productNameLabel.getFont());
                copyProductNameLabel[index].setPreferredSize(productNameLabel.getPreferredSize());
                copyProductPanels.add(copyProductNameLabel[index]);

                copyProductImageLabel[index] = new javax.swing.JLabel();
                copyProductImageLabel[index].setIcon(new javax.swing.ImageIcon(productImge.get(index)));
                copyProductImageLabel[index].setPreferredSize(productImageLabel.getPreferredSize());
                copyProductPanels.add(copyProductImageLabel[index]);
                
                copyPriceLabel[index] = new javax.swing.JLabel();
                copyPriceLabel[index].setFont(priceLabel.getFont());
                copyPriceLabel[index].setText(priceLabel.getText());
                copyPriceLabel[index].setPreferredSize(priceLabel.getPreferredSize());
                copyProductPanels.add(copyPriceLabel[index]);
                
                copyProductPriceLabel[index] = new javax.swing.JLabel();
                copyProductPriceLabel[index].setHorizontalAlignment(productPriceLabel.getHorizontalAlignment());
                copyProductPriceLabel[index].setFont(productPriceLabel.getFont());
                copyProductPriceLabel[index].setText(productPriceLabel.getText());
                copyProductPriceLabel[index].setPreferredSize(productPriceLabel.getPreferredSize());
                copyProductPanels.add(copyProductPriceLabel[index]);
                
                copyQtyLabel[index] = new javax.swing.JLabel();
                copyQtyLabel[index].setFont(qtyLabel.getFont());
                copyQtyLabel[index].setText(qtyLabel.getText());
                copyQtyLabel[index].setPreferredSize(qtyLabel.getPreferredSize());
                copyProductPanels.add(copyQtyLabel[index]);
                
                copyProductQtySpinner[index] = new javax.swing.JSpinner();
                copyProductQtySpinner[index].setFont(productQtySpinner.getFont());
                copyProductQtySpinner[index].setPreferredSize(productQtySpinner.getPreferredSize());
                copyProductPanels.add(copyProductQtySpinner[index]);
                
                productListPartPanel.add(copyProductPanels);
                index++;
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    private void resizePanel(int imgQty) {
        int col = 3; // Default value
        int width = ((productPanelPrototype.getPreferredSize().width + 25) * col);
        int height = ((productPanelPrototype.getPreferredSize().height + 25) * (imgQty / col));
        productListPartPanel.setPreferredSize(new java.awt.Dimension(width, height));
    }
    
    private int countImage(File folder) {
//        productName.clear();
        int count = 0;
        File[] files = folder.listFiles();
        if (files == null) return 0;

        for (File file : files) {
            if (file.isDirectory()) {
                count += countImage(file);
            } 
            else {
                String fileName = file.getName();
                if (fileName.toLowerCase().endsWith(".jpg")) {
                    productName.add(fileName.substring(0, fileName.lastIndexOf('.')));
                    productImge.add(getClass().getResource("/images/" + file.getParentFile().getName() + "/" + fileName));
                    count++;
                }
            }
        }
        return count;
    }
    
}
