/**
 *
 * @author BLAXK
 */
public class TemperatureConverter extends javax.swing.JFrame {

    /**
     * Creates new form CTFrame
     */
    public TemperatureConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CelsiusValue = new javax.swing.JTextField();
        CelsiusLabel = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        FahrenheitLabel = new javax.swing.JLabel();
        FahrenheitValue = new javax.swing.JTextField();
        ConvertButton = new javax.swing.JButton();
        TempModeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        CelsiusValue.setBackground(new java.awt.Color(255, 255, 102));
        CelsiusValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CelsiusValue.setForeground(new java.awt.Color(0, 0, 0));
        CelsiusValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CelsiusValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CelsiusValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CelsiusValueFocusGained(evt);
            }
        });
        CelsiusValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelsiusValueKeyTyped(evt);
            }
        });

        CelsiusLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CelsiusLabel.setForeground(new java.awt.Color(0, 0, 0));
        CelsiusLabel.setText("Celcious");

        ClearButton.setBackground(new java.awt.Color(255, 102, 51));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Clear");
        ClearButton.setToolTipText("");
        ClearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        FahrenheitLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FahrenheitLabel.setForeground(new java.awt.Color(0, 0, 0));
        FahrenheitLabel.setText("Fahrenheit");

        FahrenheitValue.setBackground(new java.awt.Color(153, 255, 153));
        FahrenheitValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FahrenheitValue.setForeground(new java.awt.Color(0, 0, 0));
        FahrenheitValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FahrenheitValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FahrenheitValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FahrenheitValueFocusGained(evt);
            }
        });
        FahrenheitValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FahrenheitValueKeyTyped(evt);
            }
        });

        ConvertButton.setBackground(new java.awt.Color(255, 153, 51));
        ConvertButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConvertButton.setForeground(new java.awt.Color(0, 0, 0));
        ConvertButton.setText("Convert");
        ConvertButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });

        TempModeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TempModeLabel.setForeground(new java.awt.Color(0, 0, 0));
        TempModeLabel.setText("(°C) Mode");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CelsiusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CelsiusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FahrenheitValue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(TempModeLabel)))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TempModeLabel)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CelsiusValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(CelsiusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FahrenheitValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed
        if (CelsiusValue.getText().isEmpty() && TempModeLabel.getText().contains("C") 
                || FahrenheitValue.getText().isEmpty() && TempModeLabel.getText().contains("F")) {    
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the numbers!!!" , "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else {
            if(TempModeLabel.getText().contains("C")) {
                FahrenheitValue.setText(TempConverter('F', Double.parseDouble(CelsiusValue.getText())));
            }
            else {
                CelsiusValue.setText(TempConverter('C', Double.parseDouble(FahrenheitValue.getText())));
            }
        }
    }//GEN-LAST:event_ConvertButtonActionPerformed

    private void NumbersOnly(javax.swing.JTextField component, java.awt.event.KeyEvent evt) {
        char val = evt.getKeyChar();
        if (component.getText().contains(".") && val == '.') {
            evt.consume();
        }
        
         ((javax.swing.text.AbstractDocument) component.getDocument()).setDocumentFilter(new javax.swing.text.DocumentFilter() {
            @Override
            public void insertString(javax.swing.text.DocumentFilter.FilterBypass fb, int offset, String string,  javax.swing.text.AttributeSet attr)
                    throws javax.swing.text.BadLocationException {
                if (string.matches("[0-9.]+") || string.equals("")) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(javax.swing.text.DocumentFilter.FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs)
                    throws  javax.swing.text.BadLocationException {
                if (text.matches("[0-9.]+") || text.equals("")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }
    
    private String TempConverter(char mode, double degree) {
        switch (mode) {
            case 'F' :
                return String.format("%.3f", (degree * 9/5) + 32);
            case 'C' :
                return String.format("%.3f", (degree - 32) * 5/9);
            default :
                return "0";
        }
    }
    
    private void CelsiusValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelsiusValueKeyTyped

        NumbersOnly(CelsiusValue, evt);
    }//GEN-LAST:event_CelsiusValueKeyTyped

    private void FahrenheitValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FahrenheitValueKeyTyped

        NumbersOnly(FahrenheitValue, evt);
    }//GEN-LAST:event_FahrenheitValueKeyTyped

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        CelsiusValue.setText("");
        FahrenheitValue.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CelsiusValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CelsiusValueFocusGained
        TempModeLabel.setText("(°C) Mode");
    }//GEN-LAST:event_CelsiusValueFocusGained

    private void FahrenheitValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FahrenheitValueFocusGained
        TempModeLabel.setText("(°F) Mode");
    }//GEN-LAST:event_FahrenheitValueFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CelsiusLabel;
    private javax.swing.JTextField CelsiusValue;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ConvertButton;
    private javax.swing.JLabel FahrenheitLabel;
    private javax.swing.JTextField FahrenheitValue;
    private javax.swing.JLabel TempModeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
