package easymath.main;

/**
 *
 * @author BLAXK
 */

public class EasyMathGame extends javax.swing.JFrame {

    /**
     * Creates new form EasyMathGame
     */
    public EasyMathGame() {
        initComponents();
        setLocationRelativeTo(this);
        soundController = new SoundController(this);
        setQuestionLabel(creatRandomQuestion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPartPanel = new javax.swing.JPanel();
        answerTextField = new javax.swing.JTextField();
        questionLabel = new javax.swing.JLabel();
        answerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        topPartPanel = new javax.swing.JPanel();
        gameNameLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Math Game");
        setResizable(false);

        mainPartPanel.setBackground(new java.awt.Color(0, 0, 0));

        answerTextField.setBackground(new java.awt.Color(255, 255, 255));
        answerTextField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        answerTextField.setForeground(new java.awt.Color(0, 0, 0));
        answerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Answer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        answerTextField.setOpaque(true);
        answerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                answerTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                answerTextFieldKeyTyped(evt);
            }
        });

        questionLabel.setBackground(new java.awt.Color(255, 255, 255));
        questionLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(0, 0, 0));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        questionLabel.setFocusable(false);
        questionLabel.setOpaque(true);

        answerButton.setBackground(new java.awt.Color(102, 255, 51));
        answerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        answerButton.setForeground(new java.awt.Color(0, 0, 0));
        answerButton.setText("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 0, 51));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        topPartPanel.setBackground(new java.awt.Color(0, 0, 0));

        gameNameLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        gameNameLabel.setForeground(new java.awt.Color(0, 255, 204));
        gameNameLabel.setText("Easy Math Game");

        scoreLabel.setBackground(new java.awt.Color(0, 0, 0));
        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 0));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("0");
        scoreLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        scoreLabel.setOpaque(true);

        scoreProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        scoreProgressBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scoreProgressBar.setForeground(new java.awt.Color(0, 0, 0));
        scoreProgressBar.setMaximum(10);
        scoreProgressBar.setToolTipText("");
        scoreProgressBar.setAutoscrolls(true);
        scoreProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 5));
        scoreProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scoreProgressBar.setOpaque(true);
        scoreProgressBar.setStringPainted(true);

        javax.swing.GroupLayout topPartPanelLayout = new javax.swing.GroupLayout(topPartPanel);
        topPartPanel.setLayout(topPartPanelLayout);
        topPartPanelLayout.setHorizontalGroup(
            topPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPartPanelLayout.createSequentialGroup()
                        .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPartPanelLayout.setVerticalGroup(
            topPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topPartPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPartPanelLayout = new javax.swing.GroupLayout(mainPartPanel);
        mainPartPanel.setLayout(mainPartPanelLayout);
        mainPartPanelLayout.setHorizontalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPartPanelLayout.setVerticalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addComponent(topPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        checkAnswer();
    }//GEN-LAST:event_answerButtonActionPerformed

    private void answerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerTextFieldKeyTyped
        numberOnly(evt);
    }//GEN-LAST:event_answerTextFieldKeyTyped

    private void answerTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerTextFieldKeyReleased
        setAnswerTextField(numberFormat(getAnswerTextField()));
    }//GEN-LAST:event_answerTextFieldKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyMathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyMathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyMathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyMathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyMathGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JTextField answerTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JPanel mainPartPanel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JProgressBar scoreProgressBar;
    private javax.swing.JPanel topPartPanel;
    // End of variables declaration//GEN-END:variables
    private SoundController  soundController;
    private int score = 0;
    
    public String getAnswerTextField() {
        return answerTextField.getText();
    }
    
    public int getCorrectAnswer() {
       String expression = getQuestionLabel()
               .replace("\u0078", "\u002A")
               .replace("\u00F7", "\u002F")
               .replaceAll("[\u2713\u2718,]", "")
               .trim();
       net.objecthunter.exp4j.Expression e = new net.objecthunter.exp4j.ExpressionBuilder(expression).build();
        return (int) e.evaluate();
    }
    
    public String getQuestionLabel() {
        return questionLabel.getText();
    }
    
    private void setAnswerTextField(String text) {
        answerTextField.setText(text);
    }

    private void setQuestionLabel(String question) {
        questionLabel.setText(question);
    }

    private void setScoreLabel(String point) {
        scoreLabel.setText(point);
    }

    private void setScoreProgressBar(int val) {
        scoreProgressBar.setValue(val);
    }
    
    private void setCorrectAnswer(boolean isCorrect) {
        if(isCorrect) {
            playSound(0, 2000);
            answerButton.setEnabled(false);
            questionLabel.setForeground(java.awt.Color.GREEN);
            setQuestionLabel(numberFormat(Integer.toString(getCorrectAnswer())) + "\u2713");
            setScoreLabel(Integer.toString(++score));
            setScoreProgressBar(score);
            return;
        }
        playSound(1, 2000);
        answerButton.setEnabled(false);
        questionLabel.setForeground(java.awt.Color.RED);
        setQuestionLabel(numberFormat(Integer.toString(getCorrectAnswer())) + "\u2718");
    }
    
    private void resetComponent(boolean reset) {
        if(reset) {
            score = 0;
            setScoreLabel("0");
            setScoreProgressBar(score);        
        }
        answerButton.setEnabled(true);
        questionLabel.setForeground(java.awt.Color.BLACK);
        setQuestionLabel(creatRandomQuestion());
        setAnswerTextField("");
    }
    
    private void checkAnswer() {
        if(getAnswerTextField().isEmpty() || getAnswerTextField().equals("\u002D")){
            callOptionPane("Please enter your answer", "Answer Required", 2);
        }
        else {
            setCorrectAnswer(toInteger(getAnswerTextField()) == getCorrectAnswer());
        }
    }
    
    public String creatRandomQuestion() {
        java.util.Random random = new java.util.Random(); 
        StringBuilder expression = new StringBuilder();
        int operatorQty = random.nextInt(4); 
        char[] operators = { 
            '\u002B', // (+)
            '\u002D', // (-)
            '\u0078',  // (x)
            '\u00F7'  // (÷)
        };
        expression.append(random.nextInt(100) + 1);
        
        for (int i = 0; i <= operatorQty; i++) {
            expression.append(" ");
            expression.append(operators[random.nextInt(operators.length)]);
            expression.append(" ");
            expression.append(random.nextInt(100) + 1);
        }
        return expression.toString();
    }
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  message, title, type);
    }
    
    public int toInteger(String val) {
        return Integer.parseInt(val.replace(",", ""));
    }
    
    private String numberFormat(String val) {
        try{
            if (!val.isEmpty() && val != null) {
                return new java.text.DecimalFormat("#,###").format(toInteger(val));
            }
        }
        catch (NumberFormatException e) {
            return val;
        }
        return "";
    }
    
    private void numberOnly(java.awt.event.KeyEvent evt) {
        char val = evt.getKeyChar();
        
        if (!Character.isDigit(val)) {
            if (val != '\u002D' || answerTextField.getCaretPosition() != 0) {
                evt.consume(); 
            } 
        }
    }
    
    private void playSound(int selectSound, int sleepTime) {
        soundController.play(selectSound);
        new Thread(() -> {
                try {
                    Thread.sleep(sleepTime);
                    if(score == scoreProgressBar.getMaximum()) {
                        soundController.play(2);
                        callOptionPane("Congratulations, you're genius!", "Congratulations", 1);
                        resetComponent(true);
                    }
                    resetComponent(false);
                } 
                catch (Exception e) {
                    callOptionPane("Error", e.toString(), 0);
                }
            }).start();
    }    
}
