package com.github.blaxk3.student.grade;

/**
 *
 * @author BLAXK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPartPanel = new javax.swing.JPanel();
        stdGradeLabel = new javax.swing.JLabel();
        infoPartPanel = new javax.swing.JPanel();
        stdIDTextField = new javax.swing.JTextField();
        fNameTextField = new javax.swing.JTextField();
        sNameTextField = new javax.swing.JTextField();
        scoreSpinner = new javax.swing.JSpinner();
        retePartPanel = new javax.swing.JPanel();
        rateLabel = new javax.swing.JLabel();
        gradeASpinner = new javax.swing.JSpinner();
        gradeBPSpinner = new javax.swing.JSpinner();
        gradeBSpinner = new javax.swing.JSpinner();
        gradeCPSpinner = new javax.swing.JSpinner();
        gradeCSpinner = new javax.swing.JSpinner();
        gradeDPSpinner = new javax.swing.JSpinner();
        gradeDSpinner = new javax.swing.JSpinner();
        gradeFSpinner = new javax.swing.JSpinner();
        resetRateButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        showDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grade");

        mainPartPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPartPanel.setToolTipText("");

        stdGradeLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        stdGradeLabel.setForeground(new java.awt.Color(0, 0, 0));
        stdGradeLabel.setText("Student Grade");

        infoPartPanel.setBackground(new java.awt.Color(204, 204, 204));

        stdIDTextField.setBackground(new java.awt.Color(255, 255, 255));
        stdIDTextField.setForeground(new java.awt.Color(0, 0, 0));
        stdIDTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        stdIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDTextFieldActionPerformed(evt);
            }
        });
        stdIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stdIDTextFieldKeyTyped(evt);
            }
        });

        fNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        fNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        fNameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        fNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameTextFieldKeyTyped(evt);
            }
        });

        sNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        sNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        sNameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sure Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        sNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameTextFieldActionPerformed(evt);
            }
        });
        sNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sNameTextFieldKeyTyped(evt);
            }
        });

        scoreSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scoreSpinner.setModel(new javax.swing.SpinnerNumberModel());
        scoreSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        retePartPanel.setBackground(new java.awt.Color(255, 255, 153));

        rateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rateLabel.setForeground(new java.awt.Color(0, 0, 0));
        rateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rateLabel.setText("Rate");

        gradeASpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeASpinner.setModel(new javax.swing.SpinnerNumberModel(90, null, null, 1));
        gradeASpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeBPSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeBPSpinner.setModel(new javax.swing.SpinnerNumberModel(85, null, null, 1));
        gradeBPSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "B+", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeBSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeBSpinner.setModel(new javax.swing.SpinnerNumberModel(80, null, null, 1));
        gradeBSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "B", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeCPSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeCPSpinner.setModel(new javax.swing.SpinnerNumberModel(75, null, null, 1));
        gradeCPSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C+", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeCSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeCSpinner.setModel(new javax.swing.SpinnerNumberModel(70, null, null, 1));
        gradeCSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeDPSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeDPSpinner.setModel(new javax.swing.SpinnerNumberModel(65, null, null, 1));
        gradeDPSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "D+", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeDSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeDSpinner.setModel(new javax.swing.SpinnerNumberModel(60, null, null, 1));
        gradeDSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "D", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        gradeFSpinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeFSpinner.setModel(new javax.swing.SpinnerNumberModel(55, null, null, 1));
        gradeFSpinner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "F", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        resetRateButton.setBackground(new java.awt.Color(255, 153, 51));
        resetRateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetRateButton.setForeground(new java.awt.Color(0, 0, 0));
        resetRateButton.setText("Reset");
        resetRateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout retePartPanelLayout = new javax.swing.GroupLayout(retePartPanel);
        retePartPanel.setLayout(retePartPanelLayout);
        retePartPanelLayout.setHorizontalGroup(
            retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retePartPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(retePartPanelLayout.createSequentialGroup()
                        .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gradeDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeCSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradeDPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeFSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(retePartPanelLayout.createSequentialGroup()
                        .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gradeBSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeASpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradeBPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeCPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(retePartPanelLayout.createSequentialGroup()
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(retePartPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(resetRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(retePartPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        retePartPanelLayout.setVerticalGroup(
            retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retePartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeASpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeBPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeBSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeCPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeCSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeDPSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(retePartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeFSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resetRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout infoPartPanelLayout = new javax.swing.GroupLayout(infoPartPanel);
        infoPartPanel.setLayout(infoPartPanelLayout);
        infoPartPanelLayout.setHorizontalGroup(
            infoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPartPanelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(infoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(retePartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        infoPartPanelLayout.setVerticalGroup(
            infoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPartPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(infoPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPartPanelLayout.createSequentialGroup()
                        .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(sNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(scoreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(retePartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        goButton.setBackground(new java.awt.Color(51, 255, 51));
        goButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        goButton.setForeground(new java.awt.Color(0, 0, 0));
        goButton.setText("Go");
        goButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        showDataButton.setBackground(new java.awt.Color(102, 0, 255));
        showDataButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        showDataButton.setForeground(new java.awt.Color(0, 0, 0));
        showDataButton.setText("Show Data");
        showDataButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPartPanelLayout = new javax.swing.GroupLayout(mainPartPanel);
        mainPartPanel.setLayout(mainPartPanelLayout);
        mainPartPanelLayout.setHorizontalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPartPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPartPanelLayout.setVerticalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if(!getStudentID().isEmpty()) {
            new Database(this, 'a');
            return;
        }
        callOptionPane("Please enter the student_id", "Error", 0);
    }//GEN-LAST:event_goButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void fNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTextFieldKeyTyped
        if(getFirstName().length() == 50) {
            evt.consume();
        }
        characterOnly(evt);
    }//GEN-LAST:event_fNameTextFieldKeyTyped

    private void stdIDTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdIDTextFieldKeyTyped
        if(getStudentID().length() == 20) {
            evt.consume();
        }
        numberOnly(evt);
    }//GEN-LAST:event_stdIDTextFieldKeyTyped

    private void sNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sNameTextFieldKeyTyped
         if(getSurname().length() == 50) {
            evt.consume();
        }
        characterOnly(evt);
    }//GEN-LAST:event_sNameTextFieldKeyTyped

    private void showDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataButtonActionPerformed
        new Database(this, 's');
    }//GEN-LAST:event_showDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JButton goButton;
    private javax.swing.JSpinner gradeASpinner;
    private javax.swing.JSpinner gradeBPSpinner;
    private javax.swing.JSpinner gradeBSpinner;
    private javax.swing.JSpinner gradeCPSpinner;
    private javax.swing.JSpinner gradeCSpinner;
    private javax.swing.JSpinner gradeDPSpinner;
    private javax.swing.JSpinner gradeDSpinner;
    private javax.swing.JSpinner gradeFSpinner;
    private javax.swing.JPanel infoPartPanel;
    private javax.swing.JPanel mainPartPanel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JButton resetRateButton;
    private javax.swing.JPanel retePartPanel;
    private javax.swing.JTextField sNameTextField;
    private javax.swing.JSpinner scoreSpinner;
    private javax.swing.JButton showDataButton;
    private javax.swing.JLabel stdGradeLabel;
    private javax.swing.JTextField stdIDTextField;
    // End of variables declaration//GEN-END:variables

    private String getStudentID() {
        return stdIDTextField.getText();
    }
    
    private String getFirstName() {
        return fNameTextField.getText();
    }
    
    private String getSurname() {
        return sNameTextField.getText();
    }
    
    private int getScore() {
        return ((Number) scoreSpinner.getValue()).intValue();
    }
    
    private String gradeCalculate() {
        javax.swing.JSpinner[] spinners = {
            gradeASpinner,
            gradeBPSpinner,
            gradeBSpinner,
            gradeCPSpinner,
            gradeCSpinner,
            gradeDPSpinner,
            gradeDSpinner,
            gradeFSpinner
        };
        
        for(javax.swing.JSpinner sp : spinners) {
            String grade = ((javax.swing.border.TitledBorder) sp.getBorder()).getTitle();
            float rate = ((Number) sp.getValue()).floatValue();
            
            if(getScore() >= rate || grade.contains("F")) {
                return grade;
            }
        }
        return null;
    }
        
    protected String[] studentData() {
        return new String[] {getStudentID(), getFirstName(), getSurname(), gradeCalculate()};
    }
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  message, title, type);
    }
    
    private void numberOnly(java.awt.event.KeyEvent evt) {
        char val = evt.getKeyChar();

        if (!Character.isDigit(val)) {
            evt.consume();
        }
    }
    
    private void characterOnly(java.awt.event.KeyEvent evt) {
        char val = evt.getKeyChar();
        if (String.valueOf(val).matches("[^a-zA-Z]")) {
            evt.consume();
        }
    }
}
