import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author BLAXK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        alertLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        inputInfoLabel = new javax.swing.JLabel();
        inputTextfield = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        verifierButton = new javax.swing.JButton();
        numericButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mixed Textfield Action");
        setName("frame"); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        alertLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        alertLabel.setForeground(new java.awt.Color(255, 0, 0));
        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        inputPanel.setBackground(new java.awt.Color(153, 255, 255));

        inputInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputInfoLabel.setForeground(new java.awt.Color(0, 0, 0));
        inputInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputInfoLabel.setText("Enter what you think (Press Enter)");

        inputTextfield.setBackground(new java.awt.Color(255, 255, 255));
        inputTextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputTextfield.setForeground(new java.awt.Color(0, 0, 0));
        inputTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextfieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(inputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(inputInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(inputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        resetButton.setBackground(new java.awt.Color(153, 153, 255));
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(0, 0, 0));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        verifierButton.setBackground(new java.awt.Color(255, 255, 51));
        verifierButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verifierButton.setForeground(new java.awt.Color(0, 0, 0));
        verifierButton.setText("Verifier");
        verifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifierButtonActionPerformed(evt);
            }
        });

        numericButton.setBackground(new java.awt.Color(255, 51, 255));
        numericButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numericButton.setForeground(new java.awt.Color(0, 0, 0));
        numericButton.setText("Numeric");
        numericButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numericButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(verifierButton)
                            .addGap(28, 28, 28)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numericButton))
                            .addGap(28, 28, 28)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numericButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextfieldKeyPressed
        
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            String text = inputTextfield.getText();
            
            if (inputTextfield.getText().isEmpty()) {
                alertLabel.setText("Please enter something!");
                JOptionPane.showMessageDialog(this, "Please enter something!", "Alert", 2);
                
                if(!numericButton.isEnabled()) {
                    alertLabel.setText("Characters has been blocked!");
                }
                else {
                    alertLabel.setText("");
                }
                return;
            }
            
            if (!verifierButton.isEnabled() && !inputTextfield.getInputVerifier().verify(inputTextfield)) {
                alertLabel.setText("Enter at least 3 characters");
                JOptionPane.showMessageDialog(this, "Enter at least 3 characters");
                alertLabel.setText("");
                return;
            }
            
            if (text.matches("\\d+") || numericButton.isEnabled()) {
                System.out.println("You typed : " + text);
                JOptionPane.showMessageDialog(this, "You typed : " + text);
            } else {

                if (!numericButton.isEnabled()) {
                    NumericFilter();
                    alertLabel.setText("Input Number Only!");
                    inputInfoLabel.setText("Enter number 0-9 (Press Enter)");
                    inputTextfield.setText("");
                    JOptionPane.showMessageDialog(this, alertLabel.getText());
                    alertLabel.setText("Characters has been blocked!");
                }
            }
        }
    }//GEN-LAST:event_inputTextfieldKeyPressed

    private void setTextfieldVerifier() {
        inputTextfield.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((javax.swing.JTextField) input).getText().trim();
                return text.length() >= 3;
            }
        });
    }

    private void NumericFilter() {

        ((AbstractDocument) inputTextfield.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                if (string.matches("[0-9]+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if (text.matches("[0-9]+") || text.equals("")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    private void resetComponent(boolean verifier, boolean numeric) {

        if (verifier) {
            inputTextfield.setInputVerifier(null);
        }

        if (numeric) {
            inputTextfield.setDocument(new PlainDocument());
        }

        alertLabel.setText("");
        inputInfoLabel.setText("Enter what you think (Press Enter)");
        inputTextfield.setText("");
        verifierButton.setEnabled(verifier);
        numericButton.setEnabled(numeric);
    }


    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        resetComponent(true, true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void verifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifierButtonActionPerformed
        resetComponent(false, true);
        setTextfieldVerifier();
    }//GEN-LAST:event_verifierButtonActionPerformed

    private void numericButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numericButtonActionPerformed
        resetComponent(true, false);
    }//GEN-LAST:event_numericButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel inputInfoLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputTextfield;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton numericButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton verifierButton;
    // End of variables declaration//GEN-END:variables
}
