import java.awt.Color;
import java.util.Random;

/**
 *
 * @author BLAXK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        handleCurrentEventLabel = new javax.swing.JLabel();
        mouseEventPanel = new javax.swing.JPanel();
        clickLabel = new javax.swing.JLabel();
        exitedLabel = new javax.swing.JLabel();
        enteredLabel = new javax.swing.JLabel();
        pressedLabel = new javax.swing.JLabel();
        releasedLabel = new javax.swing.JLabel();
        mouseMotionPanel = new javax.swing.JPanel();
        moveLabel = new javax.swing.JLabel();
        draggedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mouse Event");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        infoLabel.setBackground(new java.awt.Color(255, 255, 255));
        infoLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Move mouse over badge");
        infoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoLabel.setOpaque(true);

        handleCurrentEventLabel.setBackground(new java.awt.Color(255, 255, 255));
        handleCurrentEventLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        handleCurrentEventLabel.setForeground(new java.awt.Color(0, 0, 0));
        handleCurrentEventLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        handleCurrentEventLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Current Envent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        handleCurrentEventLabel.setOpaque(true);

        mouseEventPanel.setBackground(new java.awt.Color(255, 255, 255));
        mouseEventPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mouse Event", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        clickLabel.setBackground(new java.awt.Color(255, 255, 255));
        clickLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clickLabel.setForeground(new java.awt.Color(0, 0, 0));
        clickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickLabel.setText("Clicked");
        clickLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        clickLabel.setOpaque(true);
        clickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickLabelMouseClicked(evt);
            }
        });

        exitedLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitedLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitedLabel.setForeground(new java.awt.Color(0, 0, 0));
        exitedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitedLabel.setText("Exited");
        exitedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        exitedLabel.setOpaque(true);
        exitedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitedLabelMouseExited(evt);
            }
        });

        enteredLabel.setBackground(new java.awt.Color(255, 255, 255));
        enteredLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enteredLabel.setForeground(new java.awt.Color(0, 0, 0));
        enteredLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enteredLabel.setText("Entered");
        enteredLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        enteredLabel.setOpaque(true);
        enteredLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enteredLabelMouseEntered(evt);
            }
        });

        pressedLabel.setBackground(new java.awt.Color(255, 255, 255));
        pressedLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pressedLabel.setForeground(new java.awt.Color(0, 0, 0));
        pressedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pressedLabel.setText("Pressed");
        pressedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pressedLabel.setOpaque(true);
        pressedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressedLabelMousePressed(evt);
            }
        });

        releasedLabel.setBackground(new java.awt.Color(255, 255, 255));
        releasedLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        releasedLabel.setForeground(new java.awt.Color(0, 0, 0));
        releasedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        releasedLabel.setText("Released");
        releasedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        releasedLabel.setOpaque(true);
        releasedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                releasedLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout mouseEventPanelLayout = new javax.swing.GroupLayout(mouseEventPanel);
        mouseEventPanel.setLayout(mouseEventPanelLayout);
        mouseEventPanelLayout.setHorizontalGroup(
            mouseEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mouseEventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mouseEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mouseEventPanelLayout.createSequentialGroup()
                        .addComponent(exitedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pressedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mouseEventPanelLayout.createSequentialGroup()
                        .addComponent(clickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enteredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(mouseEventPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(releasedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mouseEventPanelLayout.setVerticalGroup(
            mouseEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mouseEventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mouseEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mouseEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pressedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(releasedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mouseMotionPanel.setBackground(new java.awt.Color(255, 255, 255));
        mouseMotionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mouse Motion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        moveLabel.setBackground(new java.awt.Color(255, 255, 255));
        moveLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        moveLabel.setForeground(new java.awt.Color(0, 0, 0));
        moveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moveLabel.setText("Move");
        moveLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        moveLabel.setOpaque(true);
        moveLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moveLabelMouseMoved(evt);
            }
        });

        draggedLabel.setBackground(new java.awt.Color(255, 255, 255));
        draggedLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        draggedLabel.setForeground(new java.awt.Color(0, 0, 0));
        draggedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        draggedLabel.setText("Dragged");
        draggedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        draggedLabel.setOpaque(true);
        draggedLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                draggedLabelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout mouseMotionPanelLayout = new javax.swing.GroupLayout(mouseMotionPanel);
        mouseMotionPanel.setLayout(mouseMotionPanelLayout);
        mouseMotionPanelLayout.setHorizontalGroup(
            mouseMotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mouseMotionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(draggedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mouseMotionPanelLayout.setVerticalGroup(
            mouseMotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mouseMotionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mouseMotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(draggedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mouseEventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mouseMotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(handleCurrentEventLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(handleCurrentEventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(mouseEventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mouseMotionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Color randomColor() {
        Random rand = new Random();
        return new Color(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256));
    }

    private void clickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickLabelMouseClicked
        handleCurrentEventLabel.setText("Mouse Cliked Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_clickLabelMouseClicked

    private void pressedLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressedLabelMousePressed
        handleCurrentEventLabel.setText("Mouse Pressed Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_pressedLabelMousePressed

    private void moveLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveLabelMouseMoved
        handleCurrentEventLabel.setText("Mouse Motion Moved Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_moveLabelMouseMoved

    private void exitedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitedLabelMouseExited
        handleCurrentEventLabel.setText("Mouse Exited Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_exitedLabelMouseExited

    private void enteredLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enteredLabelMouseEntered
        handleCurrentEventLabel.setText("Mouse Entered Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_enteredLabelMouseEntered

    private void draggedLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draggedLabelMouseDragged
        handleCurrentEventLabel.setText("Motion Dragged Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_draggedLabelMouseDragged

    private void releasedLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releasedLabelMouseReleased
        handleCurrentEventLabel.setText("Mouse Released Event");
        mainPanel.setBackground(randomColor());
    }//GEN-LAST:event_releasedLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickLabel;
    private javax.swing.JLabel draggedLabel;
    private javax.swing.JLabel enteredLabel;
    private javax.swing.JLabel exitedLabel;
    private javax.swing.JLabel handleCurrentEventLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mouseEventPanel;
    private javax.swing.JPanel mouseMotionPanel;
    private javax.swing.JLabel moveLabel;
    private javax.swing.JLabel pressedLabel;
    private javax.swing.JLabel releasedLabel;
    // End of variables declaration//GEN-END:variables
}
