/**
 *
 * @author BLAXK
 */
public class FoodShop extends javax.swing.JFrame {

    /**
     * Creates new form FoodShop
     */
    public FoodShop() {
        initComponents();
        setLocationRelativeTo(this);
        realTimePriceDisplayTextFieldUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPartPanel = new javax.swing.JPanel();
        ShopNameLabel = new javax.swing.JLabel();
        OrderPartPanel = new javax.swing.JPanel();
        MenuComboBox = new javax.swing.JComboBox<>();
        ImageMenuLabel = new javax.swing.JLabel();
        PricesLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        PriceDisplayTextField = new javax.swing.JTextField();
        QuantityInputTextField = new javax.swing.JTextField();
        CurrencyLabel = new javax.swing.JLabel();
        OptionPartPanel = new javax.swing.JPanel();
        DineinCheckBox = new javax.swing.JCheckBox();
        TakeAwayCheckBox = new javax.swing.JCheckBox();
        ImageOptionLabel = new javax.swing.JLabel();
        OrderButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CK Fast Food");
        setResizable(false);

        MainPartPanel.setBackground(new java.awt.Color(51, 51, 51));

        ShopNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ShopNameLabel.setForeground(new java.awt.Color(51, 102, 255));
        ShopNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShopNameLabel.setText("CK Fast Food");

        OrderPartPanel.setBackground(new java.awt.Color(102, 204, 255));
        OrderPartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome To CK Fast Food", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        MenuComboBox.setBackground(new java.awt.Color(255, 255, 255));
        MenuComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuComboBox.setForeground(new java.awt.Color(0, 0, 0));
        MenuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CK Menu", "Chicken Drumstick", "Cola", "French Fries", "Hamburger", "Ice Cream", " " }));
        MenuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComboBoxActionPerformed(evt);
            }
        });

        ImageMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/200x200px/original-ck.jpg"))); // NOI18N

        PricesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PricesLabel.setForeground(new java.awt.Color(0, 0, 0));
        PricesLabel.setText("Prices");

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityLabel.setForeground(new java.awt.Color(0, 0, 0));
        QuantityLabel.setText("Quantity");

        PriceDisplayTextField.setEditable(false);
        PriceDisplayTextField.setBackground(new java.awt.Color(255, 255, 255));
        PriceDisplayTextField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        PriceDisplayTextField.setForeground(new java.awt.Color(0, 0, 0));
        PriceDisplayTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PriceDisplayTextField.setFocusable(false);

        QuantityInputTextField.setEditable(false);
        QuantityInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        QuantityInputTextField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        QuantityInputTextField.setForeground(new java.awt.Color(0, 0, 0));
        QuantityInputTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QuantityInputTextField.setEnabled(false);
        QuantityInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantityInputTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityInputTextFieldKeyTyped(evt);
            }
        });

        CurrencyLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CurrencyLabel.setForeground(new java.awt.Color(0, 0, 0));
        CurrencyLabel.setText("฿");

        javax.swing.GroupLayout OrderPartPanelLayout = new javax.swing.GroupLayout(OrderPartPanel);
        OrderPartPanel.setLayout(OrderPartPanelLayout);
        OrderPartPanelLayout.setHorizontalGroup(
            OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImageMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OrderPartPanelLayout.createSequentialGroup()
                        .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantityInputTextField))
                    .addGroup(OrderPartPanelLayout.createSequentialGroup()
                        .addComponent(PricesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PriceDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrencyLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        OrderPartPanelLayout.setVerticalGroup(
            OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPartPanelLayout.createSequentialGroup()
                .addGroup(OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderPartPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImageMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addGroup(OrderPartPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(MenuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(OrderPartPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PricesLabel)
                            .addComponent(PriceDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrencyLabel))
                        .addGap(38, 38, 38)
                        .addGroup(OrderPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantityInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantityLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        OptionPartPanel.setBackground(new java.awt.Color(255, 153, 153));
        OptionPartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DineinCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        DineinCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        DineinCheckBox.setText("Dine in");
        DineinCheckBox.setEnabled(false);
        DineinCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineinCheckBoxActionPerformed(evt);
            }
        });

        TakeAwayCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TakeAwayCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        TakeAwayCheckBox.setText("Take away");
        TakeAwayCheckBox.setEnabled(false);
        TakeAwayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeAwayCheckBoxActionPerformed(evt);
            }
        });

        ImageOptionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/200x200px/ck-thinking.png"))); // NOI18N

        OrderButton.setBackground(new java.awt.Color(51, 255, 51));
        OrderButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(0, 0, 0));
        OrderButton.setText("Order");
        OrderButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        OrderButton.setEnabled(false);
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(255, 153, 51));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Clear");
        ClearButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setText("Exit");
        ExitButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionPartPanelLayout = new javax.swing.GroupLayout(OptionPartPanel);
        OptionPartPanel.setLayout(OptionPartPanelLayout);
        OptionPartPanelLayout.setHorizontalGroup(
            OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TakeAwayCheckBox)
                    .addComponent(DineinCheckBox))
                .addGroup(OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OptionPartPanelLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OptionPartPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ImageOptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OptionPartPanelLayout.setVerticalGroup(
            OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageOptionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OptionPartPanelLayout.createSequentialGroup()
                .addGroup(OptionPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionPartPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OptionPartPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(DineinCheckBox)
                        .addGap(30, 30, 30)
                        .addComponent(TakeAwayCheckBox)))
                .addGap(28, 28, 28)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPartPanelLayout = new javax.swing.GroupLayout(MainPartPanel);
        MainPartPanel.setLayout(MainPartPanelLayout);
        MainPartPanelLayout.setHorizontalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OptionPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OrderPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPartPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ShopNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        MainPartPanelLayout.setVerticalGroup(
            MainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShopNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptionPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void realTimePriceDisplayTextFieldUpdate() {
        QuantityInputTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updatePrice();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updatePrice();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updatePrice();
            }

            private void updatePrice() {
                String qty = getQuantityInputTextField().replace(",", "");
                if (qty.isEmpty()) {
                    setPriceDisplayTextField("");
                    return;
                }

                int totalPrice= getPrice() * Integer.parseInt(qty);
                String formatted = new java.text.DecimalFormat("#,###").format(totalPrice);
                setPriceDisplayTextField(formatted);
            }
        });
    }
    
    public void resetComponent() {
        MenuComboBox.setSelectedIndex(0);
        setPrice(0);
        setImageMenuLabel("/resource/images/200x200px/original-ck.jpg");
         setImageOptionLabel("/resource/images/200x200px/ck-thinking.png");
        setPriceDisplayTextField("");
        setQuantityInputTextField("");
        setEnableQuantityInputTextField(false);
        DineinCheckBox.setSelected(false);
        TakeAwayCheckBox.setSelected(false);
    }
    
    public int getPrice() {
        return price;
    }
    
    public String getMenuComboBox() {  
        return MenuComboBox.getSelectedItem().toString();
    }
    
    public String getPriceDisplayTextField() {
        return PriceDisplayTextField.getText();
    }
    
    public String getQuantityInputTextField() {
        return QuantityInputTextField.getText();
    }
    
    private void setPrice(int price) {
        this.price = price;
    }
    
    private void setEnableOrderButton(boolean status) {
        OrderButton.setEnabled(status);
    }
    
    private void setEnableCheckBoxComponent(boolean status) {
        DineinCheckBox.setEnabled(status);
        TakeAwayCheckBox.setEnabled(status);
        
        if(DineinCheckBox.isSelected()) {
            TakeAwayCheckBox.setEnabled(false);
            setImageOptionLabel("/resource/images/200x200px/ck-fastwork.png");
            setEnableOrderButton(status);
        } 
        else if (TakeAwayCheckBox.isSelected()) {
            DineinCheckBox.setEnabled(false);
            setImageOptionLabel("/resource/images/200x200px/ck-fastdrive.png");
            setEnableOrderButton(status);
        }
        else {
            setImageOptionLabel("/resource/images/200x200px/ck-thinking.png");
            setEnableOrderButton(false);
        }
    }
    
    private void setEnableQuantityInputTextField(boolean status) {
        QuantityInputTextField.setEnabled(status);
        QuantityInputTextField.setEditable(status );
    }
    
    private void setImageMenuLabel(String path) {
        ImageMenuLabel.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(path))
        );
    }
    
    private void setImageOptionLabel(String path) {
        ImageOptionLabel.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(path))
        );
    }
    
    private void setQuantityInputTextField(String val) {
        QuantityInputTextField.setText(val);
    }
    
    private void setPriceDisplayTextField(String price) {
        PriceDisplayTextField.setText(price);
    }
    
    private void DineinCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineinCheckBoxActionPerformed
        setEnableCheckBoxComponent(true);
    }//GEN-LAST:event_DineinCheckBoxActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        if(!getQuantityInputTextField().isEmpty()) { 
            OrderDetailDialog odd = new OrderDetailDialog(this);
            odd.setLocationRelativeTo(this);
            odd.setVisible(true);
            return;
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter quantity!!" , "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void MenuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComboBoxActionPerformed
        switch(getMenuComboBox()) {
            case "Chicken Drumstick" :
                setPrice(45);
                setImageMenuLabel("/resource/images/200x200px/ck-chicken-drumstick.png");
                setPriceDisplayTextField("45");
                setQuantityInputTextField("1");
                setEnableQuantityInputTextField(true);
                setEnableCheckBoxComponent(true);
                break;
            case "Cola" :
                setPrice(20);
                setImageMenuLabel("/resource/images/200x200px/ck-cola.png");
                setPriceDisplayTextField("20");
                setQuantityInputTextField("1");
                setEnableQuantityInputTextField(true);
                setEnableCheckBoxComponent(true);
                break;
            case "French Fries" :
                setPrice(39);
                setImageMenuLabel("/resource/images/200x200px/ck-french-fries.png");
                setPriceDisplayTextField("39");
                setQuantityInputTextField("1");
                setEnableQuantityInputTextField(true);
                setEnableCheckBoxComponent(true);
                break;
            case "Hamburger" :
                setPrice(69);
                setImageMenuLabel("/resource/images/200x200px/ck-hamburger.png");
                setPriceDisplayTextField("69");
                setQuantityInputTextField("1");
                setEnableQuantityInputTextField(true);
                setEnableCheckBoxComponent(true);
                break;
            case "Ice Cream" :
                setPrice(25);
                setImageMenuLabel("/resource/images/200x200px/ck-ice-cream.png");
                setPriceDisplayTextField("25");
                setQuantityInputTextField("1");
                setEnableQuantityInputTextField(true);
                setEnableCheckBoxComponent(true);
                break;
            default :
                resetComponent();
                setEnableCheckBoxComponent(false);
        }
    }//GEN-LAST:event_MenuComboBoxActionPerformed

    private void QuantityInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityInputTextFieldKeyTyped
        char val = evt.getKeyChar();
        if (!Character.isDigit(val)) {
            evt.consume();
        }
    }//GEN-LAST:event_QuantityInputTextFieldKeyTyped

    private void QuantityInputTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityInputTextFieldKeyReleased
        String text = getQuantityInputTextField().replace(",", "");
        if (text.isEmpty()) return;
        setQuantityInputTextField(
                new java.text.DecimalFormat("#,###").format(Integer.parseInt(text))
        );    
    }//GEN-LAST:event_QuantityInputTextFieldKeyReleased

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        resetComponent();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void TakeAwayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeAwayCheckBoxActionPerformed
        setEnableCheckBoxComponent(true);
    }//GEN-LAST:event_TakeAwayCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodShop().setVisible(true);
            }
        });
    }

    private int price;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel CurrencyLabel;
    private javax.swing.JCheckBox DineinCheckBox;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel ImageMenuLabel;
    private javax.swing.JLabel ImageOptionLabel;
    private javax.swing.JPanel MainPartPanel;
    private javax.swing.JComboBox<String> MenuComboBox;
    private javax.swing.JPanel OptionPartPanel;
    private javax.swing.JButton OrderButton;
    private javax.swing.JPanel OrderPartPanel;
    private javax.swing.JTextField PriceDisplayTextField;
    private javax.swing.JLabel PricesLabel;
    private javax.swing.JTextField QuantityInputTextField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JLabel ShopNameLabel;
    private javax.swing.JCheckBox TakeAwayCheckBox;
    // End of variables declaration//GEN-END:variables
}
