/**
 *
 * @author BLAXK
 */
public class OrderDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public OrderDetailDialog(FoodShop foodShop) {
        this.foodShop = foodShop;
        initComponents();
        setMenuNameLabel(foodShop.getMenuComboBox());
        setMunuQuantityLabel("X" + foodShop.getQuantityInputTextField());
        setPriceLabel(foodShop.getPriceDisplayTextField() + " ฿");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPartDialogPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        ImageLabel = new javax.swing.JLabel();
        DetailPartDialogPanel = new javax.swing.JPanel();
        MenuQuantitytLabel = new javax.swing.JLabel();
        OrderDetailLabel = new javax.swing.JLabel();
        MenuNameLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        ThanksLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order Detail");
        setModal(true);
        setResizable(false);

        MainPartDialogPanel.setBackground(new java.awt.Color(204, 255, 204));

        CancelButton.setBackground(new java.awt.Color(255, 0, 0));
        CancelButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setBackground(new java.awt.Color(102, 255, 0));
        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ConfirmButton.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmButton.setText("Confirm");
        ConfirmButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/200x200px/ck-thanks.png"))); // NOI18N

        DetailPartDialogPanel.setBackground(new java.awt.Color(255, 255, 255));

        MenuQuantitytLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MenuQuantitytLabel.setForeground(new java.awt.Color(0, 0, 0));
        MenuQuantitytLabel.setText("x0");

        OrderDetailLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        OrderDetailLabel.setForeground(new java.awt.Color(0, 0, 0));
        OrderDetailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderDetailLabel.setText("Order Detail");

        MenuNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MenuNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        MenuNameLabel.setText("MenuName");

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalLabel.setText("Total :");

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        PriceLabel.setText("0");

        ThanksLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ThanksLabel.setForeground(new java.awt.Color(0, 0, 0));
        ThanksLabel.setText("Thank you for your support :)");

        javax.swing.GroupLayout DetailPartDialogPanelLayout = new javax.swing.GroupLayout(DetailPartDialogPanel);
        DetailPartDialogPanel.setLayout(DetailPartDialogPanelLayout);
        DetailPartDialogPanelLayout.setHorizontalGroup(
            DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderDetailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                        .addGroup(DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(ThanksLabel))
                            .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                                .addComponent(TotalLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                        .addComponent(MenuNameLabel)
                        .addGap(28, 28, 28)
                        .addComponent(MenuQuantitytLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DetailPartDialogPanelLayout.setVerticalGroup(
            DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPartDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrderDetailLabel)
                .addGap(18, 18, 18)
                .addGroup(DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuNameLabel)
                    .addComponent(MenuQuantitytLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(DetailPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel)
                    .addComponent(PriceLabel))
                .addGap(18, 18, 18)
                .addComponent(ThanksLabel)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout MainPartDialogPanelLayout = new javax.swing.GroupLayout(MainPartDialogPanel);
        MainPartDialogPanel.setLayout(MainPartDialogPanelLayout);
        MainPartDialogPanelLayout.setHorizontalGroup(
            MainPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartDialogPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetailPartDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPartDialogPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        MainPartDialogPanelLayout.setVerticalGroup(
            MainPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPartDialogPanelLayout.createSequentialGroup()
                .addGroup(MainPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPartDialogPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DetailPartDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainPartDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPartDialogPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPartDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setMenuNameLabel(String  menuName) {
        MenuNameLabel.setText(menuName);
    }
    
    private void setMunuQuantityLabel(String  qty) {
        MenuQuantitytLabel.setText(qty);
    }
     
    private void setPriceLabel(String  price) {
        PriceLabel.setText(price);
    }
        
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        foodShop.resetComponent();
        this.dispose();
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private FoodShop foodShop;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JPanel DetailPartDialogPanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel MainPartDialogPanel;
    private javax.swing.JLabel MenuNameLabel;
    private javax.swing.JLabel MenuQuantitytLabel;
    private javax.swing.JLabel OrderDetailLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel ThanksLabel;
    private javax.swing.JLabel TotalLabel;
    // End of variables declaration//GEN-END:variables
}
