package string.menu;

/**
 *
 * @author BLAXK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPartPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        buttonPartPanel = new javax.swing.JPanel();
        wordCountButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();
        changeWordButton = new javax.swing.JButton();
        wordConcatButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Function Menu");
        setResizable(false);

        mainPartPanel.setBackground(new java.awt.Color(255, 255, 255));

        menuLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(0, 0, 0));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("String Menu");

        buttonPartPanel.setBackground(new java.awt.Color(255, 255, 255));

        wordCountButton.setBackground(new java.awt.Color(255, 102, 153));
        wordCountButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wordCountButton.setForeground(new java.awt.Color(0, 0, 0));
        wordCountButton.setText("Word Count");
        wordCountButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wordCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordCountButtonActionPerformed(evt);
            }
        });

        replaceButton.setBackground(new java.awt.Color(255, 204, 51));
        replaceButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        replaceButton.setForeground(new java.awt.Color(0, 0, 0));
        replaceButton.setText("Replace");
        replaceButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        reverseButton.setBackground(new java.awt.Color(102, 255, 0));
        reverseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reverseButton.setForeground(new java.awt.Color(0, 0, 0));
        reverseButton.setText("Reverse");
        reverseButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseButtonActionPerformed(evt);
            }
        });

        changeWordButton.setBackground(new java.awt.Color(0, 255, 204));
        changeWordButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeWordButton.setForeground(new java.awt.Color(0, 0, 0));
        changeWordButton.setText("Change Word");
        changeWordButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changeWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeWordButtonActionPerformed(evt);
            }
        });

        wordConcatButton.setBackground(new java.awt.Color(102, 0, 255));
        wordConcatButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wordConcatButton.setForeground(new java.awt.Color(0, 0, 0));
        wordConcatButton.setText("Word Concat");
        wordConcatButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wordConcatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordConcatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPartPanelLayout = new javax.swing.GroupLayout(buttonPartPanel);
        buttonPartPanel.setLayout(buttonPartPanelLayout);
        buttonPartPanelLayout.setHorizontalGroup(
            buttonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPartPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(buttonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordConcatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reverseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        buttonPartPanelLayout.setVerticalGroup(
            buttonPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPartPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(wordCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reverseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wordConcatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPartPanelLayout = new javax.swing.GroupLayout(mainPartPanel);
        mainPartPanel.setLayout(mainPartPanelLayout);
        mainPartPanelLayout.setHorizontalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPartPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPartPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        mainPartPanelLayout.setVerticalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        callDialog("Replace");
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void wordCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordCountButtonActionPerformed
        callDialog("Count");
    }//GEN-LAST:event_wordCountButtonActionPerformed

    private void reverseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseButtonActionPerformed
        callDialog("Reverse");
    }//GEN-LAST:event_reverseButtonActionPerformed

    private void changeWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeWordButtonActionPerformed
        callDialog("Change");
    }//GEN-LAST:event_changeWordButtonActionPerformed

    private void wordConcatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordConcatButtonActionPerformed
        callDialog("Concat");
    }//GEN-LAST:event_wordConcatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPartPanel;
    private javax.swing.JButton changeWordButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel mainPartPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton replaceButton;
    private javax.swing.JButton reverseButton;
    private javax.swing.JButton wordConcatButton;
    private javax.swing.JButton wordCountButton;
    // End of variables declaration//GEN-END:variables

    private void callDialog(String functionName) {
       StringFunction sf = new StringFunction(functionName);
       sf.setLocationRelativeTo(this);
       sf.setVisible(true);
    }
}
