package string.menu;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author BLAXK
 */
public class StringFunction extends javax.swing.JDialog {

    /**
     * Creates new form StringFunction
     */
    public StringFunction(String functionName) {
        this.functionName = functionName;
        borderTitle = getScrollPaneBorderTitle();
        initComponents();
        setTitle(functionName + " Function");
        setFunctionLabel(functionName + " Function");
        setFunctionButton(functionName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPartPanel = new javax.swing.JPanel();
        functionLabel = new javax.swing.JLabel();
        inputScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea1 = new javax.swing.JTextArea();
        inputScrollPane2 = new javax.swing.JScrollPane();
        inputTextArea2 = new javax.swing.JTextArea();
        inputScrollPane3 = new javax.swing.JScrollPane();
        inputTextArea3 = new javax.swing.JTextArea();
        resultScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea1 = new javax.swing.JTextArea();
        resultScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea2 = new javax.swing.JTextArea();
        sampleTextCheckBox = new javax.swing.JCheckBox();
        functionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        mainPartPanel.setBackground(new java.awt.Color(255, 255, 255));

        functionLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(0, 0, 0));
        functionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        functionLabel.setText("Function");

        inputScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, borderTitle[0], javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0)));

        inputTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        inputTextArea1.setColumns(20);
        inputTextArea1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        inputTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        inputTextArea1.setLineWrap(true);
        inputTextArea1.setRows(5);
        inputTextArea1.setWrapStyleWord(true);
        inputTextArea1.setBorder(null);
        inputScrollPane1.setViewportView(inputTextArea1);

        inputScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, borderTitle[1], javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0)));

        inputTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        inputTextArea2.setColumns(20);
        inputTextArea2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        inputTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        inputTextArea2.setLineWrap(true);
        inputTextArea2.setRows(5);
        inputTextArea2.setWrapStyleWord(true);
        inputTextArea2.setBorder(null);
        inputTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTextArea2KeyTyped(evt);
            }
        });
        inputScrollPane2.setViewportView(inputTextArea2);

        inputScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, borderTitle[2], javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0)));
        inputScrollPane2.setVisible(false);

        inputTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        inputTextArea3.setColumns(20);
        inputTextArea3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        inputTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        inputTextArea3.setLineWrap(true);
        inputTextArea3.setRows(5);
        inputTextArea3.setWrapStyleWord(true);
        inputTextArea3.setBorder(null);
        inputTextArea3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTextArea3KeyTyped(evt);
            }
        });
        inputScrollPane3.setViewportView(inputTextArea3);

        resultScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, borderTitle[3], javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0)));

        resultTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        resultTextArea1.setColumns(20);
        resultTextArea1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        resultTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        resultTextArea1.setLineWrap(true);
        resultTextArea1.setRows(5);
        resultTextArea1.setWrapStyleWord(true);
        resultTextArea1.setBorder(null);
        resultScrollPane1.setViewportView(resultTextArea1);

        resultScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, borderTitle[4], javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0)));
        showAdditionalComponent();

        resultTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        resultTextArea2.setColumns(20);
        resultTextArea2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        resultTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        resultTextArea2.setLineWrap(true);
        resultTextArea2.setRows(5);
        resultTextArea2.setWrapStyleWord(true);
        resultTextArea2.setBorder(null);
        resultScrollPane2.setViewportView(resultTextArea2);

        sampleTextCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sampleTextCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        sampleTextCheckBox.setText("Sample Text");
        sampleTextCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sampleTextCheckBoxItemStateChanged(evt);
            }
        });

        functionButton.setBackground(new java.awt.Color(102, 255, 0));
        functionButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        functionButton.setForeground(new java.awt.Color(0, 0, 0));
        functionButton.setText("Button");
        functionButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        functionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPartPanelLayout = new javax.swing.GroupLayout(mainPartPanel);
        mainPartPanel.setLayout(mainPartPanelLayout);
        mainPartPanelLayout.setHorizontalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(functionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPartPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sampleTextCheckBox)
                            .addGroup(mainPartPanelLayout.createSequentialGroup()
                                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                    .addComponent(inputScrollPane1))
                                .addGap(36, 36, 36)
                                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainPartPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(functionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPartPanelLayout.setVerticalGroup(
            mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPartPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(functionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(inputScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(mainPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(inputScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleTextCheckBox)
                .addGap(29, 29, 29)
                .addComponent(functionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void functionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionButtonActionPerformed
        callFunction(functionName);
    }//GEN-LAST:event_functionButtonActionPerformed

    private void sampleTextCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sampleTextCheckBoxItemStateChanged
        if(evt.getStateChange() == evt.SELECTED) {
            setInputTextArea1(getSampleText());
        }
        else {
            setInputTextArea1("");
        }
    }//GEN-LAST:event_sampleTextCheckBoxItemStateChanged

    private void inputTextArea2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextArea2KeyTyped
        if(functionName.equals("Replace")) {
            if(inputTextArea2.getText().length() >= 1) {
                    evt.consume();
            }          
        }
    }//GEN-LAST:event_inputTextArea2KeyTyped

    private void inputTextArea3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextArea3KeyTyped
        if(functionName.equals("Replace")) {
            if(inputTextArea3.getText().length() >= 1) {
                    evt.consume();
            }          
        }
    }//GEN-LAST:event_inputTextArea3KeyTyped

    private String functionName;
    private String[] borderTitle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton functionButton;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JScrollPane inputScrollPane1;
    private javax.swing.JScrollPane inputScrollPane2;
    private javax.swing.JScrollPane inputScrollPane3;
    private javax.swing.JTextArea inputTextArea1;
    private javax.swing.JTextArea inputTextArea2;
    private javax.swing.JTextArea inputTextArea3;
    private javax.swing.JPanel mainPartPanel;
    private javax.swing.JScrollPane resultScrollPane1;
    private javax.swing.JScrollPane resultScrollPane2;
    private javax.swing.JTextArea resultTextArea1;
    private javax.swing.JTextArea resultTextArea2;
    private javax.swing.JCheckBox sampleTextCheckBox;
    // End of variables declaration//GEN-END:variables
    
    private String getSampleText() {
        try (InputStream inputStream = getClass().getResourceAsStream("/resources/text/Sample.txt")) {
            if (inputStream == null) {
                callOptionPane("File not found", "Error", 0);
                return null;
            }
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                sb.append(line).append("\n");
            }
            return sb.toString();
        } 
        catch (Exception e) {
            callOptionPane(e.toString(), "Error", 0);
            this.dispose();
            return null;
        }
    }
    
    private String[] getScrollPaneBorderTitle() {
        switch(functionName) {
            case "Reverse" :
                return new String[] {"Text Input", "",  "","Result of words", "Result of characters"};
            case "Replace" :
                return new String[] {"Text Input", "The character want to replace", "The characters to be replaced", "Result" , ""};
            case "Change" :
                return new String[] {"Text Input", "The word want to change", "The words to be changed", "Result" , ""};
            case "Concat" :
                return new String[] {"Text Input 1", "Text Input 2", "", "Result", ""};
            default :
                return new String[] {"Text Input", "",  "", "Result", ""};
        }
    }
    
    private String  getInputTextArea1 () {
        return inputTextArea1.getText();
    }
    
    private String  getInputTextArea2 () {
        return inputTextArea2.getText();
    }
     
    private String  getInputTextArea3 () {
        return inputTextArea3.getText();
    }
    
    private void setInputTextArea1(String text) {
        inputTextArea1.setText(text);
    }
    
    private void setResultTextArea1(String text) {
        resultTextArea1.setText(text);
    }
    
    private void setResultTextArea2(String text) {
        resultTextArea2.setText(text);
    }
    
    private void setFunctionLabel(String text) {
        functionLabel.setText(text);
    }
    
    private void setFunctionButton(String text) {
        functionButton.setText(text);
    }
        
    private void callFunction(String functionName) {
        switch(functionName) {
            case "Count" :
                wordCountFunction();
                break;
            case "Concat" :  
                wordConcatFunction();
                break;
            case "Change" :
                changeWordFunction();
                break;
            case "Replace" :
                replaceFunction();
                break;
            case "Reverse" :
                reverseFunction();
                break;
        }
    }
    
    public void callOptionPane(String message, String title, int type) {
        javax.swing.JOptionPane.showMessageDialog(this,  message, title, type);
    }
    
    private void showAdditionalComponent() {
        switch(functionName) {
            case "Reverse" :
                inputScrollPane2.setVisible(false);
                inputScrollPane3.setVisible(false);
                resultScrollPane2.setVisible(true);
                break;
            case "Replace" :
            case "Change" :
                inputScrollPane2.setVisible(true);
                inputScrollPane3.setVisible(true);
                inputScrollPane3.setVisible(true);
                resultScrollPane2.setVisible(false);
                break;
            case "Concat" :
                inputScrollPane2.setVisible(true);
                inputScrollPane3.setVisible(false);
                resultScrollPane2.setVisible(false);
                break;
            default :
                inputScrollPane2.setVisible(false);
                inputScrollPane3.setVisible(false);
                resultScrollPane2.setVisible(false);
        }
    }
    
    private void wordCountFunction() {
        String text = getInputTextArea1();
        int charCount = text.replaceAll("\\r?\\n", "").length();
        String[] words = text.trim().split("\\s+");
        int wordCount = (text.trim().isEmpty()) ? 0 : words.length;
        String[] sentences = text.split("[.!?]+");
        int sentenceCount = (text.trim().isEmpty()) ? 0 : sentences.length;
        String[] paragraphs = text.split("\\n+");
        int paragraphCount = (text.trim().isEmpty()) ? 0 : paragraphs.length;
        int spaceCount = 0;
        
        for (char c : text.toCharArray()) {
            if (c == ' ') {
                spaceCount++;
            }
        }
        setResultTextArea1(
            "Characters : " + charCount +
            "\nWords : " + wordCount +
            "\nSentences : " + sentenceCount +
            "\nParagraphs : " + paragraphCount +
            "\nSpaces : " + spaceCount
        );
    }
    
    private void replaceFunction() {
        setResultTextArea1(getInputTextArea1().replace(getInputTextArea2(), getInputTextArea3()));
    }
    
    private void reverseFunction() {
        setResultTextArea1(String.join(" ", java.util.Arrays.asList(getInputTextArea1().split("\\s+")).reversed()));
        setResultTextArea2(new StringBuilder(getInputTextArea1()).reverse().toString().trim());
    }
    
    private void changeWordFunction() {
        setResultTextArea1(getInputTextArea1().replaceAll("\\b" + getInputTextArea2() + "\\b", getInputTextArea3()));
    }
    
    private void wordConcatFunction() {
        setResultTextArea1(getInputTextArea1().concat(" " + getInputTextArea2()));
    }
}
